Repository ministryofjustice/laa-assess-crime-forms, pull requests merged in 2024-04, with the labels that each got.

#392 Stop referring to specific ruby classes in event payload
  app/jobs/pull_latest_version_data.rb
  app/models/event.rb
  spec/jobs/pull_latest_version_data_spec.rb
  spec/models/event_spec.rb
Labels: approved

#397 CRM457-1285: Host whitelisting
  config/environments/production.rb
  helm_deploy/templates/deployment.yaml
Labels: approved

#400 Bug fix dummy user creation
  app/models/event.rb
Labels: approved

#399 CRM457-1181: Separate name fields
  app/view_models/prior_authority/v1/application_details/base_card.rb
  app/view_models/prior_authority/v1/application_details/case_contact_card.rb
  app/view_models/prior_authority/v1/quote.rb
  db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
  db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json
  spec/factories/claims.rb
  spec/factories/prior_authority_applications.rb
  spec/view_models/nsm/v1/contact_details_spec.rb
  spec/view_models/prior_authority/v1/application_details_spec.rb
Labels: approved

#405 Do not try to save events we already have records of
  app/models/event.rb
  spec/jobs/pull_latest_version_data_spec.rb
Labels: ready for review

#403 CRM457-1303: Add utility endpoint to do an immediate sync
  .env.development
  .env.test
  app/controllers/sync_controller.rb
  config/routes.rb
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
  spec/requests/sync_spec.rb
Labels: approved

#404 CRM457-887: Request Google not to index non-production environments
  app/controllers/robots_controller.rb
  app/views/layouts/govuk_template.html.erb
  app/views/robots/allow.text
  app/views/robots/disallow.text
  config/routes.rb
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
  public/robots.txt
  spec/requests/robots_spec.rb
Labels: approved

#401 updated azure registration details and refer to new secret keys in yaml
  app/services/app_store_token_provider.rb
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
Labels: approved

#410 Try to get locking working reliably
  app/models/event.rb
Labels: ready for review

#406 CRM457-1236: Prevent rejecting or granting if adjustments have been made
  app/forms/prior_authority/decision_form.rb
  config/locales/en/prior_authority/decisions.yml
  spec/forms/prior_authority/decision_form_spec.rb
  spec/system/prior_authority/make_decision_spec.rb
Labels: approved

#412 CRM457-1327: Pub/Sub instead of cron
  .rubocop.yml
  app/controllers/sync_controller.rb
  app/jobs/pull_latest_version_data.rb
  app/jobs/pull_updates.rb
  app/services/app_store_client.rb
  app/services/app_store_subscriber.rb
  app/services/app_store_token_authenticator.rb
  app/services/http_puller.rb
  app/services/notify_app_store.rb
  app/services/notify_app_store/http_notifier.rb
  app/services/receive_application_metadata.rb
  app/services/update_submission.rb
  config/application.rb
  config/routes.rb
  config/schedule.yml
  spec/jobs/pull_updates_spec.rb
  spec/requests/sync_spec.rb
  spec/services/app_store_client_spec.rb
  spec/services/app_store_subscriber_spec.rb
  spec/services/http_puller_spec.rb
  spec/services/notify_app_store/http_notifier_spec.rb
  spec/services/notify_app_store_spec.rb
  spec/services/receive_application_metadata_spec.rb
  spec/services/update_submission_spec.rb
Labels: approved

#422 CRM457-1308: Postal evidence
  app/views/nsm/supporting_evidences/show.html.erb
  config/feature_flags.yml
  spec/system/nsm/supporting_evidence_spec.rb
Labels: approved, In QA

#413 [Snyk] Fix for 1 vulnerabilities
  Gemfile
  Gemfile.lock
Labels: approved

#414 Fix Incorrect Namespace Ref in Readme
  README.md
Labels: approved

#421 Use local app store service URL for production
  helm_deploy/values-prod.yaml
Labels: approved

#407 CRM457-1172: Add line breaks to multi-line text
  app/view_models/prior_authority/v1/application_details/alternative_quote_card.rb
  app/view_models/prior_authority/v1/application_details/base_card.rb
  app/view_models/prior_authority/v1/application_details/hearing_details_card.rb
  app/view_models/prior_authority/v1/application_details/no_alternative_quotes_card.rb
  app/view_models/prior_authority/v1/application_details/primary_quote_card.rb
  app/view_models/prior_authority/v1/application_details/reason_why_card.rb
  app/views/prior_authority/adjustments/_additional_costs.html.erb
  app/views/prior_authority/adjustments/_travel_costs.erb
  config/locales/en/prior_authority/adjustments.yml
  spec/system/prior_authority/view_adjust_quote_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
  spec/view_models/prior_authority/v1/application_details_spec.rb
Labels: approved, In QA

#423 CRM457-762: Show totals at top (and bug-fixes)
  app/mailers/nsm/feedback_messages/feedback_base.rb
  app/mailers/nsm/feedback_messages/part_granted_feedback.rb
  app/models/claim.rb
  app/view_models/nsm/v1/claim_summary.rb
  app/view_models/nsm/v1/core_cost_summary.rb
  app/views/nsm/claims/_claim_summary.html.erb
  config/locales/en/nsm/claims.yml
  db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
  db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json
  spec/mailers/nsm/feedback_messages/further_information_request_feeback_spec.rb
  spec/mailers/nsm/feedback_messages/granted_feedback_spec.rb
  spec/mailers/nsm/feedback_messages/part_granted_feedback_spec.rb
  spec/mailers/nsm/feedback_messages/provider_request_feedback_spec.rb
  spec/mailers/nsm/feedback_messages/rejected_feedback_spec.rb
  spec/mailers/nsm/submission_feedback_mailer_spec.rb
  spec/system/nsm/overview_spec.rb
  spec/view_models/nsm/v1/claim_summary_spec.rb
  spec/view_models/nsm/v1/core_cost_summary_spec.rb
Labels: approved, In QA

#425 Add envars needed for local integration
  .env.development
  Procfile.dev
Labels: ready for review

#433 CRM457-1365: Wrong timestamps
  app/view_models/nsm/v1/all_claims.rb
  app/view_models/nsm/v1/assessed_claims.rb
  app/view_models/nsm/v1/your_claims.rb
  spec/view_models/nsm/v1/all_claims_spec.rb
  spec/view_models/nsm/v1/assessed_claims_spec.rb
  spec/view_models/nsm/v1/your_claims_spec.rb
Labels: ready for review

#429 Caseworker - add environment to sentry
  config/initializers/sentry.rb
Labels: approved

#432 CRM457-917: Add circleci config for e2e tests
  .circleci/config.yml
Labels: approved

#436 CRM457-1398 Add auto scaling for pods
  helm_deploy/templates/hpa-worker.yaml
  helm_deploy/templates/hpa.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: approved

#434 CRM457-1318: Auto grant email
  app/forms/nsm/make_decision_form.rb
  app/forms/nsm/send_back_form.rb
  app/forms/prior_authority/decision_form.rb
  app/forms/prior_authority/send_back_form.rb
  app/jobs/expire_sendbacks.rb
  app/mailers/prior_authority/submission_feedback_mailer.rb
  app/services/notify_app_store.rb
  app/services/update_submission.rb
  config/application.rb
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  spec/forms/nsm/make_decision_form_spec.rb
  spec/forms/nsm/send_back_form_spec.rb
  spec/forms/prior_authority/send_back_form_spec.rb
  spec/jobs/expire_sendbacks_spec.rb
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
  spec/services/notify_app_store_spec.rb
  spec/services/update_submission_spec.rb
  spec/system/nsm/assessment_spec.rb
  spec/system/prior_authority/make_decision_spec.rb
  spec/system/prior_authority/send_back_spec.rb
Labels: approved

#440 Reduce app store calls
  app/controllers/sync_controller.rb
  app/services/app_store_client.rb
  spec/requests/sync_spec.rb
  spec/services/app_store_client_spec.rb
Labels: approved

#441 Paginate before mapping
  app/controllers/nsm/assessed_claims_controller.rb
  app/controllers/nsm/claims_controller.rb
Labels: ready for review

#442 Stop converting to arrays for pagination
  app/controllers/nsm/assessed_claims_controller.rb
  app/controllers/nsm/claims_controller.rb
  app/controllers/nsm/your_claims_controller.rb
Labels: ready for review

#443 Only send emails if a flag is set
  app/services/notify_app_store.rb
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  spec/services/notify_app_store_spec.rb
Labels: approved
