Repository ministryofjustice/laa-assess-crime-forms, pull requests merged in 2024-12, with the labels that each got.

#865 Ship youth court fee
  app/models/claim.rb
  config/feature_flags.yml
Labels: do not merge

#868 CRM457-2322: No UAT devauth, and improve UX when unknown caseworker ID
  app/forms/prior_authority/unassignment_form.rb
  app/models/event.rb
  app/models/event/unassignment.rb
  app/models/submission.rb
  app/models/user.rb
  app/view_models/nsm/v1/further_information.rb
  app/view_models/prior_authority/v1/application_details/further_information_card.rb
  app/view_models/prior_authority/v1/application_details/incorrect_information_card.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/view_models/search_result.rb
  config/feature_flags.yml
  config/locales/en/helpers.yml
  spec/models/event/unassignment_spec.rb
  spec/view_models/nsm/v1/further_information_spec.rb
Labels: approved

#875 Increase anomaly threshold
  helm_deploy/templates/ingress.yaml
Labels: ready for review

#871 CRM457-2300: Delete youth court adjustments
  app/controllers/concerns/nsm/adjustment_concern.rb
  app/controllers/nsm/additional_fees_controller.rb
  app/models/claim.rb
  app/services/nsm/adjustment_deleter.rb
  app/services/nsm/all_adjustments_deleter.rb
  app/view_models/nsm/v1/case_disposal.rb
  app/view_models/nsm/v1/youth_court_fee.rb
  app/views/nsm/additional_fees/_adjusted.html.erb
  app/views/nsm/additional_fees/confirm_delete_adjustment.html.erb
  app/views/nsm/letters_and_calls/_adjusted.html.erb
  config/locales/en/nsm/additional_fees.yml
  config/locales/en/nsm/adjustments.yml
  spec/factories/claims.rb
  spec/services/nsm/all_adjustments_deleter_spec.rb
  spec/system/nsm/additional_fees_spec.rb
  spec/system/nsm/adjustments_spec.rb
  spec/view_models/nsm/v1/case_disposal_spec.rb
Labels: approved

#876 Memoize data_for_calculation
  app/models/claim.rb
Labels: ready for review

#877 CRM457-2217: Simplify use of events
  Gemfile
  Gemfile.lock
  app/controllers/nsm/histories_controller.rb
  app/controllers/prior_authority/events_controller.rb
  app/forms/base_adjustment_form.rb
  app/forms/nsm/additional_fees_form.rb
  app/forms/nsm/disbursements_form.rb
  app/forms/nsm/letters_calls_form.rb
  app/forms/nsm/uplift/letters_and_calls_form.rb
  app/forms/nsm/uplift/remover_form.rb
  app/forms/nsm/uplift/work_items_form.rb
  app/forms/nsm/work_item_form.rb
  app/forms/nsm/youth_court_fee_form.rb
  app/forms/prior_authority/additional_cost_form.rb
  app/forms/prior_authority/service_cost_form.rb
  app/forms/prior_authority/travel_cost_form.rb
  app/models/event.rb
  app/models/event/auto_decision.rb
  app/models/event/edit.rb
  app/models/event/undo_edit.rb
  app/models/submission.rb
  app/services/adjustment_deleter_base.rb
  app/services/nsm/adjustment_deleter.rb
  app/services/nsm/all_adjustments_deleter.rb
  app/services/prior_authority/adjustment_deleter.rb
  app/view_models/nsm/v1/additional_fee.rb
  app/view_models/nsm/v1/disbursement.rb
  app/view_models/nsm/v1/letter_and_call.rb
  app/view_models/nsm/v1/work_item.rb
  app/view_models/prior_authority/v1/additional_cost.rb
  app/view_models/prior_authority/v1/quote.rb
  app/view_models/prior_authority/v1/service_cost.rb
  app/view_models/prior_authority/v1/travel_cost.rb
  config/database.yml
  db/migrate/20241213171004_remove_postgis.rb
  db/schema.rb
  doc/adjustments.md
  spec/controllers/nsm/histories_controller_spec.rb
  spec/factories/events.rb
  spec/forms/nsm/letters_calls_form_spec.rb
  spec/forms/nsm/work_item_form_spec.rb
  spec/models/event/auto_decision_spec.rb
  spec/models/event/edit_spec.rb
  spec/models/event_spec.rb
  spec/services/nsm/adjustment_deleter_spec.rb
  spec/services/nsm/all_adjustments_deleter_spec.rb
  spec/services/prior_authority/adjustment_deleter_spec.rb
  spec/system/prior_authority/history_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
  spec/view_models/prior_authority/v1/event_summary_spec.rb
Labels: approved

#879 Bump gem version
  Gemfile
  Gemfile.lock
Labels: approved

#883 CRM457-2277: Outsource S3 url generation to the gem
  Gemfile
  Gemfile.lock
  app/controllers/concerns/file_redirectable.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved

#846 CRM457-2154: add 'high value' filter to search
  app/controllers/dashboards_controller.rb
  app/controllers/nsm/searches_controller.rb
  app/forms/search_form.rb
  app/views/shared/_search.html.erb
  config/locales/en.yml
  config/locales/en/nsm/search.yml
Labels: approved
