Repository ministryofjustice/laa-assess-crime-forms, pull requests merged in 2024-09, with the labels that each got.

#742 CRM457-1956: Allow adding letters and calls when originally zero
  app/views/nsm/letters_and_calls/_index.html.erb
  config/locales/en/nsm/letters_and_calls.yml
Labels: approved, In QA

#737 CRM457-1946: Remove individual VAT figures
  app/javascript/component/nsm/letters_calls_adjustment.js
  app/view_models/nsm/v1/letter_and_call.rb
  app/view_models/nsm/v1/work_item.rb
  app/views/nsm/letters_and_calls/edit.html.erb
  config/locales/en/nsm/letters_and_calls.yml
  config/locales/en/nsm/work_items.yml
  spec/view_models/nsm/v1/letter_and_call_spec.rb
  spec/view_models/nsm/v1/work_item_spec.rb
Labels: approved, In QA

#744 CRM457-1958: Tab clicks should link to the tab bar
  app/views/nsm/adjustments/show.html.erb
  app/views/nsm/review_and_adjusts/show.html.erb
Labels: approved, In QA

#745 CRM457-1959: Standardise cost display
  app/view_models/nsm/v1/work_item.rb
  app/views/nsm/disbursements/show.html.erb
  app/views/nsm/letters_and_calls/show.html.erb
  app/views/nsm/work_items/edit.html.erb
  app/views/nsm/work_items/show.html.erb
  config/locales/en/nsm/disbursements.yml
  config/locales/en/nsm/letters_and_calls.yml
  config/locales/en/nsm/work_items.yml
  spec/system/nsm/disbursements_spec.rb
  spec/system/nsm/letters_and_calls_spec.rb
  spec/system/nsm/work_items_spec.rb
  spec/view_models/nsm/v1/work_item_spec.rb
Labels: approved, In QA

#751 CRM457-1873: Retry app store subscription
  app/services/app_store_subscriber.rb
  spec/services/app_store_subscriber_spec.rb
Labels: approved

#752 CRM457-1978: Only prioritise post-mortem pathologist reports
  app/services/prior_authority/choose_application_for_assignment.rb
  spec/services/prior_authority/choose_application_for_assignment_spec.rb
Labels: approved

#738 CRM457-1940: Move cost adjustment asterisk outside of tab panel
  app/controllers/nsm/disbursements_controller.rb
  app/controllers/nsm/letters_and_calls_controller.rb
  app/controllers/nsm/work_items_controller.rb
  app/views/nsm/review_and_adjusts/show.html.erb
  app/views/nsm/work_items/_adjusted.html.erb
  app/views/nsm/work_items/_index.html.erb
  spec/controllers/nsm/disbursements_controller_spec.rb
  spec/controllers/nsm/letters_and_calls_controller_spec.rb
Labels: approved, In QA

#757 CRM457-1973: Handle partial postcodes
  app/services/location_service.rb
  app/services/location_service/outcodes_that_straddle_the_m25.yaml
  app/services/update_submission.rb
  spec/services/location_service_spec.rb
Labels: approved, In QA

#764 CRM457-1967: Stop reading from events
  Gemfile
  Gemfile.lock
  app/models/claim.rb
  app/models/event.rb
  app/models/submission.rb
  app/services/update_submission.rb
  app/view_models/nsm/v1/claim_summary.rb
  app/view_models/prior_authority/v1/application_details.rb
  app/view_models/prior_authority/v1/decision.rb
  app/views/nsm/claim_details/show.html.erb
  app/views/nsm/claims/_claim_summary.html.erb
  db/migrate/20240916092416_add_new_attribute_to_rfi_objects.rb
  db/schema.rb
  spec/mailers/prior_authority/feedback_messages/part_granted_feedback_spec.rb
  spec/mailers/prior_authority/feedback_messages/rejected_feedback_spec.rb
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
  spec/system/nsm/overview_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
  spec/view_models/nsm/v1/claim_summary_spec.rb
Labels: approved

#762 CRM457-1954: Update search form design
  app/assets/stylesheets/custom/search.scss
  app/assets/stylesheets/local/moj.scss
  app/forms/search_form.rb
  app/javascript/application.js
  app/javascript/component/date-picker.js
  app/validators/is_a_date_validator.rb
  app/views/layouts/dashboard/_primary_navigation.html.erb
  app/views/layouts/nsm/_primary_navigation.html.erb
  app/views/layouts/prior_authority/_primary_navigation.html.erb
  app/views/shared/_search.html.erb
  config/initializers/date_and_time_formats.rb
  config/locales/en.yml
  config/locales/en/dashboards.yml
  config/locales/en/nsm/search.yml
  config/locales/en/prior_authority/search.yml
  spec/system/dashboards_spec.rb
  spec/system/nsm/search_spec.rb
  spec/system/prior_authority/search_spec.rb
Labels: approved

#758 CRM457-1969: Add new Viewer role
  app/controllers/nsm/claims_controller.rb
  app/controllers/prior_authority/applications_controller.rb
  app/models/claim.rb
  app/models/user.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/views/layouts/nsm/_primary_navigation.html.erb
  app/views/layouts/prior_authority/_primary_navigation.html.erb
  app/views/nsm/claims/_claim_summary.html.erb
  app/views/nsm/claims/your.html.erb
  app/views/prior_authority/applications/your.html.erb
  app/views/prior_authority/events/index.html.erb
  app/views/prior_authority/shared/_application_nav.html.erb
  db/seeds/caseworkers.rb
  spec/factories/users.rb
  spec/system/viewers_spec.rb
Labels: approved, In QA

#766 CRM457-1954: Disable turbo-links
  app/javascript/application.js
  app/views/home/index.html.erb
  app/views/layouts/_header_navigation.html.erb
  app/views/layouts/dashboard/_primary_navigation.html.erb
  app/views/layouts/nsm/_primary_navigation.html.erb
  app/views/layouts/prior_authority/_primary_navigation.html.erb
  app/views/prior_authority/applications/_table.html.erb
  app/views/prior_authority/shared/_application_buttons.html.erb
  app/views/shared/_search.html.erb
Labels: approved, In QA

#763 CRM457-1949 delete adjustments
  app/controllers/concerns/nsm/adjustment_concern.rb
  app/controllers/nsm/adjustments_controller.rb
  app/controllers/nsm/disbursements_controller.rb
  app/controllers/nsm/letters_and_calls_controller.rb
  app/controllers/nsm/work_items_controller.rb
  app/controllers/prior_authority/additional_costs_controller.rb
  app/controllers/prior_authority/service_costs_controller.rb
  app/controllers/prior_authority/travel_costs_controller.rb
  app/forms/nsm/delete_adjustments_form.rb
  app/models/event.rb
  app/models/event/delete_adjustments.rb
  app/services/adjustment_deleter_base.rb
  app/services/nsm/adjustment_deleter.rb
  app/services/nsm/all_adjustments_deleter.rb
  app/services/prior_authority/adjustment_deleter.rb
  app/view_models/nsm/v1/letter_and_call.rb
  app/views/nsm/adjustments/confirm_deletion_adjustments.html.erb
  app/views/nsm/adjustments/show.html.erb
  app/views/nsm/disbursements/_adjusted.html.erb
  app/views/nsm/disbursements/confirm_delete_adjustment.html.erb
  app/views/nsm/letters_and_calls/_adjusted.html.erb
  app/views/nsm/letters_and_calls/confirm_delete_adjustment.html.erb
  app/views/nsm/work_items/_adjusted.html.erb
  app/views/nsm/work_items/confirm_delete_adjustment.html.erb
  config/locales/en/events.yml
  config/locales/en/nsm/adjustments.yml
  config/locales/en/nsm/disbursements.yml
  config/locales/en/nsm/letters_and_calls.yml
  config/locales/en/nsm/work_items.yml
  config/routes.rb
  spec/factories/claims.rb
  spec/services/adjustment_deleter_base_spec.rb
  spec/services/nsm/adjustment_deleter_spec.rb
  spec/services/nsm/all_adjustments_deleter_spec.rb
  spec/system/nsm/adjustments_spec.rb
Labels: approved, In QA

#753 CRM457-1679: Validate make a decision scenarios
  app/forms/nsm/make_decision_form.rb
  app/models/claim.rb
  app/validators/adjustments_dependant_validator.rb
  app/view_models/base_with_adjustments.rb
  app/view_models/nsm/v1/core_cost_summary.rb
  app/view_models/nsm/v1/disbursement.rb
  config/locales/en/errors.yml
  spec/factories/claims.rb
  spec/forms/nsm/make_decision_form_spec.rb
  spec/system/nsm/assessment_spec.rb
  spec/validators/adjustments_dependant_validator_spec.rb
  spec/view_models/nsm/v1/disbursement_spec.rb
  spec/view_models/nsm/v1/letter_and_call_spec.rb
  spec/view_models/nsm/v1/work_item_spec.rb
Labels: approved, In QA

#772 CRM457-2033: Translations - MERGE THIS SECOND
  Gemfile
  Gemfile.lock
  app/attributes/translation_object.rb
  app/attributes/type/translated_object.rb
  app/attributes/type/translated_object_array.rb
  app/forms/base_adjustment_form.rb
  app/forms/nsm/letters_calls_form.rb
  app/forms/nsm/work_item_form.rb
  app/services/nsm/adjustment_deleter.rb
  app/view_models/base_view_model.rb
  app/view_models/nsm/v1/case_disposal.rb
  app/view_models/nsm/v1/claim_justification.rb
  app/view_models/nsm/v1/details_of_claim.rb
  app/view_models/nsm/v1/disbursement.rb
  app/view_models/nsm/v1/equality_details.rb
  app/view_models/nsm/v1/hearing_details.rb
  app/view_models/nsm/v1/letter_and_call.rb
  app/view_models/nsm/v1/work_item.rb
  config/initializers/attribute_types.rb
  spec/attributes/type/translated_object_array_spec.rb
  spec/attributes/type/translated_object_spec.rb
  spec/controllers/nsm/disbursements_controller_spec.rb
  spec/factories/claims.rb
  spec/factories/disbursements.rb
  spec/factories/work_items.rb
  spec/forms/nsm/disbursements_form_spec.rb
  spec/forms/nsm/letters_calls_form_spec.rb
  spec/forms/nsm/make_decision_form_spec.rb
  spec/forms/nsm/work_item_form_spec.rb
  spec/system/nsm/adjustments_spec.rb
  spec/system/nsm/assessment_spec.rb
  spec/system/nsm/disbursements_spec.rb
  spec/system/nsm/overview_spec.rb
  spec/system/nsm/work_items_spec.rb
  spec/view_models/base_view_model_spec.rb
  spec/view_models/nsm/v1/case_disposal_spec.rb
  spec/view_models/nsm/v1/claim_justification_spec.rb
  spec/view_models/nsm/v1/core_cost_summary_spec.rb
  spec/view_models/nsm/v1/details_of_claim_spec.rb
  spec/view_models/nsm/v1/disbursement_spec.rb
  spec/view_models/nsm/v1/equality_details_spec.rb
  spec/view_models/nsm/v1/hearing_details_spec.rb
  spec/view_models/nsm/v1/letter_and_call_spec.rb
  spec/view_models/nsm/v1/letters_and_calls_summary_spec.rb
  spec/view_models/nsm/v1/work_item_spec.rb
  spec/view_models/nsm/v1/work_items_summary_spec.rb
Labels: approved

#780 CRM457-1755: Add solidcache in production
  Gemfile
  Gemfile.lock
  config/cache.yml
  config/environments/production.rb
  db/migrate/20240925081532_add_cache_table.rb
  db/schema.rb
Labels: approved

#783 CRM457-2069: Add exception
  helm_deploy/templates/ingress.yaml
Labels: approved

#777 CRM457-2002: Expire claims and show expired claims
  app/forms/nsm/search_form.rb
  app/helpers/application_helper.rb
  app/jobs/expire_sendbacks.rb
  app/models/claim.rb
  app/view_models/nsm/v1/claim_summary.rb
  app/views/nsm/claim_details/show.html.erb
  app/views/nsm/histories/show.html.erb
  config/locales/en/events.yml
  spec/forms/nsm/search_form_spec.rb
  spec/jobs/expire_sendbacks_spec.rb
  spec/system/nsm/overview_spec.rb
Labels: ready for review

#775 CRM457-2000: New NSM send-back mechanism
  .env.test
  app/controllers/nsm/send_backs_controller.rb
  app/forms/nsm/search_form.rb
  app/forms/nsm/send_back_form.rb
  app/helpers/application_helper.rb
  app/jobs/expire_sendbacks.rb
  app/jobs/nsm/fake_assess.rb
  app/mailers/nsm/feedback_messages/further_information_request_feedback.rb
  app/models/claim.rb
  app/services/working_day_service.rb
  app/view_models/nsm/v1/claim_summary.rb
  app/views/nsm/claim_details/show.html.erb
  app/views/nsm/histories/show.html.erb
  app/views/nsm/send_backs/edit.html.erb
  config/application.rb
  config/feature_flags.yml
  config/locales/en/events.yml
  config/locales/en/nsm/send_back.yml
  spec/controllers/nsm/send_backs_controller_spec.rb
  spec/forms/nsm/search_form_spec.rb
  spec/forms/nsm/send_back_form_spec.rb
  spec/jobs/expire_sendbacks_spec.rb
  spec/mailers/nsm/feedback_messages/further_information_request_feeback_spec.rb
  spec/services/working_day_service_spec.rb
  spec/system/nsm/assessment_spec.rb
  spec/system/nsm/overview_spec.rb
Labels: ready for review

#785 CRM457-1759: Require DB SSL for RDS
  config/database.yml
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
Labels: ready for review

#784 CRM457-2063: Use 10 working day window for prior authority application send-backs
  app/forms/nsm/send_back_form.rb
  app/forms/prior_authority/send_back_form.rb
  app/jobs/expire_sendbacks.rb
  app/mailers/nsm/feedback_messages/further_information_request_feedback.rb
  app/mailers/prior_authority/feedback_messages/further_information_request_feedback.rb
  config/application.rb
  spec/forms/prior_authority/send_back_form_spec.rb
  spec/jobs/expire_sendbacks_spec.rb
  spec/jobs/prior_authority/fake_assess_spec.rb
  spec/mailers/nsm/feedback_messages/further_information_request_feeback_spec.rb
  spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
  spec/system/prior_authority/send_back_spec.rb
Labels: approved, In QA

#786 CRM457-2102: Add styling
  app/views/shared/_search.html.erb
Labels: approved

#787 CRM457-1996: access logs
  app/controllers/application_controller.rb
  app/controllers/nsm/base_controller.rb
  app/controllers/nsm/claims_controller.rb
  app/controllers/prior_authority/applications_controller.rb
  app/controllers/prior_authority/base_controller.rb
  app/models/access_log.rb
  app/models/user.rb
  db/migrate/20240930083741_create_access_logs.rb
  db/schema.rb
  lib/tasks/audit.rake
  spec/controllers/nsm/change_risks_controller_spec.rb
  spec/controllers/nsm/histories_controller_spec.rb
  spec/controllers/nsm/make_decisions_controller_spec.rb
  spec/controllers/nsm/send_backs_controller_spec.rb
  spec/controllers/nsm/unassignments_controller_spec.rb
  spec/factories/access_log.rb
  spec/lib/tasks/audit_spec.rb
  spec/system/nsm/assessment_spec.rb
  spec/system/prior_authority/make_decision_spec.rb
Labels: approved, In QA
