Repository ministryofjustice/laa-assess-crime-forms, pull requests merged in 2024-08, with the labels that each got.

#673 CRM457-1784: New sent back status
  app/forms/nsm/send_back_form.rb
  app/helpers/submission_tag_helper.rb
  app/models/claim.rb
  app/models/nsm/event/send_back.rb
  app/services/sorter.rb
  config/locales/en.yml
  config/locales/en/events.yml
  config/locales/en/nsm/your_claims.yml
  db/migrate/20240808115142_update_status.rb
  db/schema.rb
  spec/controllers/nsm/unassignments_controller_spec.rb
  spec/forms/nsm/send_back_form_spec.rb
  spec/jobs/nsm/fake_assess_spec.rb
  spec/mailers/nsm/submission_feedback_mailer_spec.rb
  spec/models/event/send_back_spec.rb
  spec/system/nsm/history_spec.rb
  spec/system/nsm/view_claims_table_spec.rb
Labels: ready for review

#675 CRM457-1836: Show prom/prog and BOI details
  app/view_models/nsm/v1/details_of_claim.rb
  app/view_models/nsm/v1/hearing_details.rb
  config/locales/en/nsm/claim_details.yml
  db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
  db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json
  spec/factories/claims.rb
  spec/view_models/nsm/v1/details_of_claim_spec.rb
  spec/view_models/nsm/v1/hearing_details_spec.rb
Labels: approved, In QA

#677 CRM457-1785: Add assessment comment to payload
  app/forms/nsm/make_decision_form.rb
  app/forms/nsm/send_back_form.rb
  app/forms/prior_authority/decision_form.rb
  db/migrate/20240809091311_backfill_assessment_comments.rb
  db/schema.rb
  spec/forms/nsm/make_decision_form_spec.rb
  spec/forms/nsm/send_back_form_spec.rb
  spec/forms/prior_authority/decision_form_spec.rb
Labels: ready for review

#680 CRM457-1847: Remove 'retry_on'
  app/services/notify_app_store.rb
  app/services/notify_event_app_store.rb
Labels: ready for review

#681 CRM457-1788: Change maat naming
  config/locales/en/prior_authority/application_details.yml
  spec/view_models/prior_authority/v1/application_details_spec.rb
Labels: approved, In QA

#684 Move perform_laters out of transactions to avoid race conditions
  app/forms/nsm/make_decision_form.rb
  app/forms/nsm/send_back_form.rb
  app/forms/prior_authority/decision_form.rb
  app/forms/prior_authority/send_back_form.rb
  app/services/update_submission.rb
Labels: approved

#689 CRM457-1866: Better date sorting
  app/services/sorter.rb
  spec/system/prior_authority/application_lists_spec.rb
Labels: ready for review

#694 CRM457-1880: Validate correctly on search dashboard
  app/controllers/dashboards_controller.rb
  app/forms/search_form.rb
  config/locales/en.yml
  config/locales/en/errors.yml
  spec/system/dashboards_spec.rb
Labels: approved

#691 Add tasks for secret rotation
  lib/tasks/db.rake
  lib/tasks/redis_sidekiq.rake
  spec/lib/tasks/redis_sidekiq_spec.rb
Labels: approved, discussion

#585 CRM457-1689: Allow changing work type
  .rubocop.yml
  app/controllers/nsm/work_items_controller.rb
  app/forms/nsm/work_item_form.rb
  app/javascript/component/nsm/work_item_adjustment.js
  app/jobs/nsm/fake_assess.rb
  app/view_models/nsm/v1/work_item.rb
  app/view_models/nsm/v1/work_item_summary.rb
  app/views/nsm/work_items/_adjusted.html.erb
  app/views/nsm/work_items/_index.html.erb
  app/views/nsm/work_items/edit.html.erb
  app/views/nsm/work_items/show.html.erb
  config/locales/en/nsm/work_items.yml
  spec/controllers/nsm/work_items_controller_spec.rb
  spec/factories/claims.rb
  spec/forms/nsm/disbursements_form_spec.rb
  spec/forms/nsm/work_item_form_spec.rb
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
  spec/system/nsm/work_items_spec.rb
  spec/view_models/nsm/v1/work_item_spec.rb
Labels: approved, In QA

#696 CRM457-1815: Make test data more realistic to fix view coverage blind spot
  spec/system/nsm/overview_spec.rb
Labels: approved

#687 CRM457-1857 remove auto-grants from select filter on CRM7 search/filter
  app/controllers/nsm/searches_controller.rb
  app/controllers/prior_authority/searches_controller.rb
  app/forms/nsm/search_form.rb
  app/forms/prior_authority/search_form.rb
  app/views/dashboards/_tab_content.html.erb
  app/views/nsm/searches/show.html.erb
  app/views/prior_authority/searches/show.html.erb
  app/views/shared/_search.html.erb
  spec/forms/nsm/search_form_spec.rb
  spec/system/nsm/search_spec.rb
  spec/system/prior_authority/search_spec.rb
Labels: approved, In QA

#692 CRM457-1860 CRM7 claim details show wrong info when rejected or granted and adjusted
  app/models/claim.rb
  app/view_models/nsm/v1/core_cost_summary.rb
  spec/factories/claims.rb
  spec/models/claims_spec.rb
  spec/view_models/nsm/v1/core_cost_summary_spec.rb
Labels: approved, In QA

#709 CRM457-1895: Resolve TODO
  app/models/claim.rb
  app/view_models/nsm/v1/core_cost_summary.rb
  app/views/nsm/review_and_adjusts/show.html.erb
  spec/view_models/nsm/v1/core_cost_summary_spec.rb
Labels: ready for review

#698 CRM457-1871: New UI for showing when work type changed
  .rubocop.yml
  app/javascript/lib/table-item-anchors.js
  app/view_models/nsm/v1/core_cost_summary.rb
  app/view_models/nsm/v1/work_item.rb
  app/view_models/nsm/v1/work_item_summary.rb
  app/views/nsm/work_items/_adjusted.html.erb
  app/views/nsm/work_items/_index.html.erb
  app/views/nsm/work_items/show.html.erb
  config/locales/en/nsm/work_items.yml
  spec/system/nsm/assessment_spec.rb
  spec/system/nsm/work_items_spec.rb
  spec/view_models/nsm/v1/core_cost_summary_spec.rb
  spec/view_models/nsm/v1/work_item_spec.rb
  spec/view_models/nsm/v1/work_items_summary_spec.rb
Labels: approved, In QA

#713 CRM457-1867: Update wording of contact details
  app/view_models/nsm/v1/contact_details.rb
  config/locales/en/nsm/claim_details.yml
  spec/view_models/nsm/v1/contact_details_spec.rb
Labels: approved, In QA

#718 CRM457-1803: Add claim state enum and use enums more
  app/forms/nsm/make_decision_form.rb
  app/forms/nsm/send_back_form.rb
  app/forms/prior_authority/send_back_form.rb
  app/jobs/expire_sendbacks.rb
  app/jobs/nsm/fake_assess.rb
  app/models/claim.rb
  app/views/nsm/make_decisions/edit.html.erb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/shared/_application_nav.html.erb
  lib/tasks/dummy_assessments.rake
  spec/mailers/nsm/submission_feedback_mailer_spec.rb
  spec/models/claims_spec.rb
  spec/models/event/auto_decision_spec.rb
  spec/services/update_submission_spec.rb
Labels: approved

#720 CRM457-1644: Claim dates
  app/models/claim.rb
  app/view_models/nsm/v1/claim_summary.rb
  app/view_models/nsm/v1/disbursement.rb
  app/views/nsm/claims/_claim_summary.html.erb
  config/locales/en/nsm/claims.yml
  spec/system/nsm/assessment_spec.rb
  spec/system/nsm/disbursements_spec.rb
  spec/view_models/nsm/v1/disbursement_spec.rb
Labels: approved, In QA

#708 CRM457-1861: Move office code question
  app/view_models/nsm/v1/contact_details.rb
  app/view_models/nsm/v1/details_of_claim.rb
  config/locales/en/nsm/claim_details.yml
  spec/view_models/nsm/v1/contact_details_spec.rb
  spec/view_models/nsm/v1/details_of_claim_spec.rb
Labels: approved, In QA

#701 CRM457-1901: Adjust how disbursement adjustments are validated
  app/forms/nsm/disbursements_form.rb
  config/locales/en/nsm/disbursements.yml
  config/locales/en/nsm/letters_and_calls.yml
  config/locales/en/nsm/work_items.yml
Labels: approved

#723 CRM457-1704: More explicit error handling for Redis errors
  config/environments/production.rb
  public/500.html
Labels: approved

#721 CRM457-1645: Show send back reason on claim details page
  app/models/claim.rb
  app/view_models/nsm/v1/claim_summary.rb
  app/views/nsm/claim_details/show.html.erb
  config/locales/en/nsm/claim_details.yml
  spec/system/nsm/assessment_spec.rb
Labels: approved, In QA

#728 CRM457-1846: Remove redundant header
  app/views/nsm/letters_and_calls/_adjusted.html.erb
Labels: approved

#729 CRM457-1935: Sent back claims show with 'Closed' nav tab highlighted
  .rubocop.yml
  app/helpers/application_helper.rb
Labels: approved, In QA

#730 CRM457-1922: Only show maat if it is provided
  app/view_models/nsm/v1/defendant_details.rb
  spec/view_models/nsm/v1/defendant_details_spec.rb
Labels: approved, In QA

#726 CMR457-1909: Add rake task for contact email update
  lib/tasks/fixes.rake
  spec/factories/claims.rb
  spec/lib/tasks/fixes_spec.rb
Labels: approved

#727 CMR457-1907: Enable maintenance mode on production
  config/feature_flags.yml
Labels: do not merge

#724 CRM457-1878: High risk claims are not auto-assigned
  app/controllers/nsm/claims_controller.rb
  app/models/claim.rb
  spec/models/claims_spec.rb
Labels: approved, In QA

#725 CRM457-1930: Resolve back button loop
  app/controllers/application_controller.rb
  app/javascript/application.js
  app/javascript/lib/table-item-anchors.js
  app/view_models/nsm/v1/disbursement.rb
  app/view_models/nsm/v1/letter_and_call.rb
  app/view_models/nsm/v1/work_item.rb
  app/views/nsm/disbursements/_adjusted.html.erb
  app/views/nsm/disbursements/_index.html.erb
  app/views/nsm/disbursements/edit.html.erb
  app/views/nsm/disbursements/show.html.erb
  app/views/nsm/letters_and_calls/edit.html.erb
  app/views/nsm/letters_and_calls/show.html.erb
  app/views/nsm/work_items/_adjusted.html.erb
  app/views/nsm/work_items/_index.html.erb
  app/views/nsm/work_items/edit.html.erb
  app/views/nsm/work_items/show.html.erb
  spec/view_models/nsm/v1/disbursement_spec.rb
  spec/view_models/nsm/v1/letter_and_call_spec.rb
  spec/view_models/nsm/v1/work_item_spec.rb
Labels: approved, In QA
