Repository ministryofjustice/laa-assess-crime-forms, pull requests merged in 2024-06, with the labels that each got.

#505 [Snyk] Security upgrade ruby from 3.3.0-alpine3.19 to 3.3.2-alpine3.19
  .circleci/config.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
Labels: ready for review

#503 [CRM457-1543] Allow part grant without comment
  app/forms/prior_authority/decision_form.rb
  config/locales/en/prior_authority/decisions.yml
  spec/system/prior_authority/make_decision_spec.rb
Labels: approved

#510 CRM457-1565: Add subheadings in email for further info and incorrect info
  app/mailers/prior_authority/feedback_messages/further_information_request_feedback.rb
  spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
Labels: approved, In QA

#519 Ensure state is also set in JSON blob
  app/forms/nsm/make_decision_form.rb
  app/forms/nsm/send_back_form.rb
  app/forms/prior_authority/decision_form.rb
  app/forms/prior_authority/send_back_form.rb
Labels: approved

#518 CRM457-1520: Manual assignment for NSM
  app/controllers/nsm/assignments_controller.rb
  app/controllers/nsm/unassignments_controller.rb
  app/forms/nsm/assignment_form.rb
  app/models/event/assignment.rb
  app/views/nsm/assignments/new.html.erb
  app/views/nsm/claims/_claim_summary.html.erb
  config/locales/en/events.yml
  config/locales/en/nsm/assignments.yml
  config/locales/en/nsm/claims.yml
  config/locales/en/nsm/unassignment.yml
  config/routes.rb
  spec/controllers/nsm/unassignments_controller_spec.rb
  spec/system/nsm/assignment_spec.rb
  spec/system/nsm/history_spec.rb
Labels: approved

#522 CRM457-1597: Allow zero times
  app/forms/prior_authority/base_cost_adjustment_form.rb
  app/forms/prior_authority/travel_cost_form.rb
  app/validators/item_type_dependant_validator.rb
  app/view_models/prior_authority/v1/application_details/primary_quote_card.rb
  app/views/prior_authority/adjustments/index.html.erb
  config/locales/en/errors.yml
  spec/system/prior_authority/adjust_additional_costs_spec.rb
  spec/system/prior_authority/adjust_service_costs_spec.rb
  spec/validators/item_type_dependant_validator_spec.rb
Labels: approved, In QA

#521 CRM457-1470: NSM readonly mode
  app/models/claim.rb
  app/views/nsm/claims/_claim_summary.html.erb
  app/views/nsm/disbursements/index.html.erb
  app/views/nsm/histories/show.html.erb
  app/views/nsm/letters_and_calls/index.html.erb
  app/views/nsm/work_items/index.html.erb
  app/views/shared/_claim_button_group.erb
  config/locales/en/nsm/claims.yml
  spec/system/nsm/assessment_spec.rb
  spec/system/nsm/assignment_spec.rb
  spec/system/nsm/disbursements_spec.rb
  spec/system/nsm/history_spec.rb
  spec/system/nsm/letters_and_calls_spec.rb
  spec/system/nsm/overview_spec.rb
  spec/system/nsm/risk_spec.rb
  spec/system/nsm/work_items_spec.rb
Labels: approved, In QA

#524 CRM457-1457: Export metrics to prometheus
  Gemfile
  Gemfile.lock
  config/initializers/prometheus.rb
  helm_deploy/templates/deployment.yaml
  helm_deploy/templates/service.yaml
Labels: approved

#531 CRM457-1618: Send to correct email
  app/mailers/nsm/feedback_messages/feedback_base.rb
  spec/mailers/nsm/feedback_messages/feedback_base_spec.rb
Labels: ready for review

#532 CRM457-1622: Fix typo
  config/locales/en/nsm/send_back.yml
  spec/controllers/nsm/send_backs_controller_spec.rb
Labels: approved, ready for review

#533 CRM457-1580: Switch service becomes Change service
  config/locales/en/assess_a_crime_form.yml
  spec/system/nsm/disbursements_spec.rb
  spec/system/nsm/letters_and_calls_spec.rb
  spec/system/nsm/work_items_spec.rb
Labels: ready for review

#534 CRM457-1478: Embedded metabase charts
  .env.test
  app/controllers/dashboards_controller.rb
  app/views/dashboards/show.html.erb
  app/views/layouts/_header_navigation.html.erb
  config/initializers/content_security_policy.rb
  config/locales/en.yml
  config/locales/en/dashboards.yml
  config/routes.rb
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
  spec/system/dashboards_spec.rb
Labels: question

#540 Replace HPA with standard replicas and RollingUpdate strategy
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  helm_deploy/templates/hpa-worker.yaml
  helm_deploy/templates/hpa.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: approved

#544 Add feature flag for insights
  app/controllers/dashboards_controller.rb
  app/views/layouts/_header_navigation.html.erb
  config/feature_flags.yml
  spec/system/dashboards_spec.rb
Labels: approved

#545 Use assess_a_crime_form layout for footer links
  app/controllers/errors_controller.rb
  app/controllers/home_controller.rb
  app/controllers/nsm/adjustments_controller.rb
  app/controllers/nsm/assignments_controller.rb
  app/controllers/nsm/base_controller.rb
  app/controllers/nsm/change_risks_controller.rb
  app/controllers/nsm/claim_details_controller.rb
  app/controllers/nsm/claims_controller.rb
  app/controllers/nsm/disbursements_controller.rb
  app/controllers/nsm/downloads_controller.rb
  app/controllers/nsm/histories_controller.rb
  app/controllers/nsm/letters_and_calls/uplifts_controller.rb
  app/controllers/nsm/letters_and_calls_controller.rb
  app/controllers/nsm/make_decisions_controller.rb
  app/controllers/nsm/send_backs_controller.rb
  app/controllers/nsm/supporting_evidences_controller.rb
  app/controllers/nsm/unassignments_controller.rb
  app/controllers/nsm/work_items/uplifts_controller.rb
  app/controllers/nsm/work_items_controller.rb
  app/controllers/users/dev_auth_controller.rb
  app/controllers/users/sessions_controller.rb
  app/views/layouts/application.html.erb
  app/views/layouts/external.html.erb
  app/views/layouts/nsm.html.erb
Labels: approved

#552 CRM457-1647: Sub-£1 values
  app/forms/prior_authority/base_cost_adjustment_form.rb
  app/validators/cost_item_type_dependant_validator.rb
  app/validators/item_type_dependant_validator.rb
  spec/validators/cost_item_type_dependant_validator_spec.rb
  spec/validators/item_type_dependant_validator_spec.rb
Labels: approved

#530 CRM457-1408: Add custom modsec error page handler
  bin/deploy
  helm_deploy/templates/custom-error-pages.yaml
  helm_deploy/templates/deployment-custom-errors.yaml
  helm_deploy/templates/ingress.yaml
  helm_deploy/templates/service.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: approved

#557 CRM457-1652: Tweak spec example description
  spec/view_models/nsm/v1/disbursement_spec.rb
Labels: approved

#558 CRM457-1650: Standardise modsec and add correct tagging
  helm_deploy/templates/ingress.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: approved

#529 CRM457-1358: Add maintenance page
  app/controllers/application_controller.rb
  config/feature_flags.yml
  config/initializers/content_security_policy.rb
  public/crest.svg
  public/gds-transport-bold.woff2
  public/gds-transport-light.woff2
  public/maintenance.html
  spec/system/maintenance_mode_spec.rb
Labels: approved, In QA

#561 CRM457-1657: Remove some Modsec rules that give false positives
  helm_deploy/templates/ingress.yaml
Labels: approved

#559 CRM457-1648: Protect against reloading unassignment form
  app/controllers/nsm/unassignments_controller.rb
  config/locales/en/nsm/unassignment.yml
  spec/controllers/nsm/unassignments_controller_spec.rb
Labels: approved, In QA

#562 CRM457-1408: custom modsec attempt 2
  bin/deploy
  helm_deploy/templates/custom-error-pages.yaml
  helm_deploy/templates/deployment-custom-errors.yaml
  helm_deploy/templates/ingress.yaml
  helm_deploy/templates/service.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: approved, In QA

#567 CRM457-1675: Fix spelling mistake
  db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
  spec/factories/claims.rb
  spec/view_models/nsm/v1/claim_justification_spec.rb
Labels: approved

#565 CRM457-1671: Remove duplicate nav
  app/views/nsm/assignments/new.html.erb
Labels: approved, In QA

#566 CRM457-1674: Fix time period config
  app/forms/nsm/work_item_form.rb
  config/locales/en/nsm/work_items.yml
Labels: approved, In QA

#578 CRM457-1579: Notify via Slack on failure
  .circleci/config.yml
Labels: ready for review

#579 CRM457-1655: Accessibility content
  Gemfile.lock
  app/views/about/accessibility/index.en.html.erb
Labels: approved, In QA

#580 CRM457-1676: Optional grant comments
  app/controllers/nsm/make_decisions_controller.rb
  app/forms/nsm/make_decision_form.rb
  app/views/nsm/make_decisions/edit.html.erb
  config/locales/en/nsm/make_decisions.yml
  spec/forms/nsm/make_decision_form_spec.rb
  spec/system/nsm/assessment_spec.rb
Labels: approved, In QA

#577 CRM457-1637: Change labels to make more consistent
  app/view_models/prior_authority/v1/additional_cost.rb
  app/views/prior_authority/adjustments/_additional_costs.html.erb
  app/views/prior_authority/applications/_primary_quote_card.html.erb
  config/locales/en/prior_authority/additional_costs.yml
  config/locales/en/prior_authority/adjustments.yml
  config/locales/en/prior_authority/application_details.yml
  config/locales/en/prior_authority/applications.yml
  config/locales/en/prior_authority/service_costs.yml
  config/locales/en/prior_authority/travel_costs.yml
  spec/system/prior_authority/adjust_additional_costs_spec.rb
  spec/system/prior_authority/adjust_service_costs_spec.rb
  spec/system/prior_authority/adjust_travel_costs_spec.rb
  spec/system/prior_authority/adjustments_spec.rb
  spec/system/prior_authority/delete_adjustments_spec.rb
  spec/system/prior_authority/view_adjust_quote_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
  spec/view_models/prior_authority/v1/additional_cost_spec.rb
Labels: approved, In QA

#581 CRM457-1691: Handle filenames with commas
  app/controllers/nsm/downloads_controller.rb
  app/controllers/prior_authority/downloads_controller.rb
  spec/system/feedback_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: ready for review

#574 Provider: Analytics Dashboard Tab (CRM4 & CRM7)
  app/controllers/dashboards_controller.rb
  app/views/dashboards/_autogrant.html.erb
  app/views/dashboards/_dashboard_iframe.html.erb
  app/views/dashboards/_prior_authority_nav.html.erb
  app/views/dashboards/_tab_content.html.erb
  config/feature_flags.yml
  config/locales/en/dashboards.yml
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
  spec/controllers/dashboard_controller_spec.rb
  spec/system/dashboards_spec.rb
Labels: approved
