Repository ministryofjustice/laa-assess-crime-forms, pull requests merged in 2024-05, with the labels that each got.

#448 Update app store url
  helm_deploy/values-dev.yaml
Labels: ready for review

#449 CRM457-1375: Open related applications in new tabs
  app/views/prior_authority/related_applications/_table.html.erb
  app/views/prior_authority/related_applications/index.html.erb
  config/locales/en/prior_authority/related_applications.yml
Labels: approved, In QA

#447 CRM457-1326: Add notes to PA applications
  app/controllers/prior_authority/notes_controller.rb
  app/forms/prior_authority/note_form.rb
  app/view_models/prior_authority/v1/event_summary.rb
  app/views/prior_authority/events/index.html.erb
  app/views/prior_authority/notes/new.html.erb
  config/locales/en/errors.yml
  config/locales/en/prior_authority/events.yml
  config/locales/en/prior_authority/notes.yml
  config/routes.rb
  spec/factories/events.rb
  spec/system/prior_authority/history_spec.rb
  spec/system/prior_authority/notes_spec.rb
  spec/view_models/prior_authority/v1/event_summary_spec.rb
Labels: approved, In QA

#451 CRM457-1313: View town
  app/view_models/prior_authority/v1/application_details/key_information_card.rb
  app/view_models/prior_authority/v1/application_details/primary_quote_card.rb
  app/view_models/prior_authority/v1/quote.rb
  config/locales/en/prior_authority/application_details.yml
  spec/factories/prior_authority_applications.rb
  spec/system/prior_authority/view_adjust_quote_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
  spec/view_models/prior_authority/v1/application_details/key_information_card_spec.rb
  spec/view_models/prior_authority/v1/application_details_spec.rb
Labels: approved, In QA

#450 CRM457-1069: Add privacy policy view, controller and link
  app/controllers/about/privacy_controller.rb
  app/views/about/privacy/index.en.html.erb
  app/views/layouts/_footer_links.html.erb
  config/routes.rb
  spec/system/privacy_policy_spec.rb
Labels: approved

#439 CRM457-1012: RFI tweaks from QA
  app/services/notify_app_store.rb
  app/services/update_submission.rb
  app/view_models/prior_authority/v1/application_details.rb
  app/view_models/prior_authority/v1/application_details/further_information_card.rb
  app/view_models/prior_authority/v1/event_summary.rb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/events/index.html.erb
  app/views/prior_authority/send_backs/show.html.erb
  config/locales/en/prior_authority/events.yml
  spec/system/prior_authority/send_back_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved, In QA

#455 CRM457-1284: Add assessment fakery
  .rubocop.yml
  Gemfile
  Gemfile.lock
  app/jobs/nsm/fake_assess.rb
  app/jobs/prior_authority/fake_assess.rb
  app/view_models/nsm/v1/details_of_claim.rb
  app/view_models/nsm/v1/equality_details.rb
  lib/tasks/dummy_assessments.rake
  spec/jobs/nsm/fake_assess_spec.rb
  spec/jobs/prior_authority/fake_assess_spec.rb
  spec/lib/tasks/dummy_assessments_spec.rb
  spec/spec_helper.rb
Labels: approved

#456 CRM457-1455: Increase prod and UAT replicaCount
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: ready for review

#457 Allow dev login in UAT
  config/feature_flags.yml
Labels: approved

#458 CRM457-1460: Hide send back button if claim is sent back
  app/models/claim.rb
  app/views/shared/_claim_button_group.erb
  spec/system/nsm/assessment_spec.rb
Labels: approved, In QA

#460 CRM457-1069: Amendments to privacy policy content
  app/views/about/privacy/index.en.html.erb
Labels: approved

#459 CRM457-1471: Switch to redis for session contents
  Gemfile
  Gemfile.lock
  config/application.rb
  config/environments/production.rb
  config/initializers/sidekiq.rb
  config/locales/en/cookies.yml
Labels: approved

#464 CRM457-850: Stop rounding down
  app/lib/number_to.rb
  app/view_models/nsm/v1/letter_and_call.rb
  app/view_models/nsm/v1/work_item.rb
  app/views/nsm/letters_and_calls/edit.html.erb
  app/views/nsm/work_items/edit.html.erb
  spec/view_models/nsm/v1/letter_and_call_spec.rb
  spec/view_models/nsm/v1/work_item_spec.rb
Labels: approved

#466 Add .snyk file for vulnerability ignores
  .circleci/config.yml
  .snyk
Labels: approved

#462 CRM457-1322: Update page names
  config/locales/en.yml
  config/locales/en/nsm/assessed_claims.yml
  config/locales/en/nsm/claims.yml
Labels: approved, In QA

#463 CRM457-1423: Move error messages and tie to a field if possible
  app/forms/base_adjustment_form.rb
  app/forms/nsm/disbursements_form.rb
  app/forms/nsm/letters_calls_form.rb
  app/forms/nsm/work_item_form.rb
  app/views/about/feedback/index.html.erb
  app/views/nsm/change_risks/edit.html.erb
  app/views/nsm/disbursements/edit.html.erb
  app/views/nsm/letters_and_calls/edit.html.erb
  app/views/nsm/letters_and_calls/uplifts/edit.html.erb
  app/views/nsm/make_decisions/edit.html.erb
  app/views/nsm/send_backs/edit.html.erb
  app/views/nsm/unassignments/edit.html.erb
  app/views/nsm/work_items/edit.html.erb
  app/views/nsm/work_items/uplifts/edit.html.erb
  app/views/prior_authority/additional_costs/edit.html.erb
  app/views/prior_authority/decisions/new.html.erb
  app/views/prior_authority/manual_assignments/new.html.erb
  app/views/prior_authority/send_backs/new.html.erb
  app/views/prior_authority/service_costs/edit.html.erb
  app/views/prior_authority/travel_costs/edit.html.erb
  app/views/prior_authority/unassignments/new.html.erb
  config/locales/en/nsm/disbursements.yml
  config/locales/en/nsm/letters_and_calls.yml
  config/locales/en/nsm/work_items.yml
  spec/forms/nsm/letters_calls_form_spec.rb
  spec/forms/nsm/work_item_form_spec.rb
  spec/system/nsm/disbursements_spec.rb
Labels: approved, In QA

#468 CRM457-1461: Show in-progress tags on "your claims" page
  app/view_models/nsm/v1/your_claims.rb
  app/views/nsm/your_claims/_your_claims_table.html.erb
  config/locales/en/nsm/your_claims.yml
  spec/view_models/nsm/v1/your_claims_spec.rb
Labels: approved, In QA

#467 CRM457-1451: Remove check all claims link
  app/views/nsm/your_claims/index.html.erb
  config/locales/en/nsm/your_claims.yml
Labels: approved, In QA

#471 CRM457-1463: Correct typo accessed -> assessed
  app/helpers/application_helper.rb
  app/views/nsm/claims/_claim_summary.html.erb
  config/locales/en/nsm/claims.yml
  spec/helpers/application_helper_spec.rb
  spec/view_models/nsm/v1/claim_summary_spec.rb
Labels: ready for review

#477 CRM457-1467: Fix floating point rounding errors
  app/attributes/integer_time_period.rb
  app/javascript/component/nsm/letters_calls_adjustment.js
  app/javascript/component/nsm/work_item_adjustment.js
  app/javascript/component/prior_authority/cost_adjustment.js
  app/javascript/component/prior_authority/travel_cost_adjustment.js
  app/view_models/nsm/v1/letter_and_call.rb
  app/view_models/nsm/v1/work_item.rb
  package.json
  spec/attributes/integer_time_period_spec.rb
  spec/view_models/nsm/v1/work_item_spec.rb
  yarn.lock
Labels: approved

#474 Modsec change to allow big data chunck
  helm_deploy/values-dev.yaml
Labels: question

#475 CRM457-1474: Amend NSM home/landing/root page to be your claims
  .circleci/config.yml
  app/controllers/about/feedback_controller.rb
  app/controllers/nsm/assessed_claims_controller.rb
  app/controllers/nsm/claims_controller.rb
  app/controllers/nsm/make_decisions_controller.rb
  app/controllers/nsm/send_backs_controller.rb
  app/controllers/nsm/unassignments_controller.rb
  app/controllers/nsm/your_claims_controller.rb
  app/models/claim.rb
  app/view_models/nsm/v1/all_claims.rb
  app/views/layouts/_header_navigation.html.erb
  app/views/layouts/_primary_navigation.html.erb
  app/views/layouts/application.html.erb
  app/views/nsm/claims/_closed_table.html.erb
  app/views/nsm/claims/_open_table.html.erb
  app/views/nsm/claims/_yours_table.html.erb
  app/views/nsm/claims/closed.html.erb
  app/views/nsm/claims/open.html.erb
  app/views/nsm/claims/your.html.erb
  app/views/shared/_claim_button_group.erb
  config/locales/en/nsm/claims.yml
  config/locales/en/nsm/closed_claims.yml
  config/locales/en/nsm/open_claims.yml
  config/locales/en/nsm/your_claims.yml
  config/routes.rb
  spec/controllers/about/feedback_controller_spec.rb
  spec/controllers/nsm/assessed_claims_controller_spec.rb
  spec/controllers/nsm/claims_controller_spec.rb
  spec/controllers/nsm/make_decisions_controller_spec.rb
  spec/controllers/nsm/send_backs_controller_spec.rb
  spec/controllers/nsm/unassignments_controller_spec.rb
  spec/controllers/nsm/your_claims_controller_spec.rb
  spec/system/accessibility_spec.rb
  spec/system/authenticating/reauthentication_spec.rb
  spec/system/nsm/assignment_spec.rb
  spec/system/nsm/risk_spec.rb
Labels: approved, In QA

#478 CRM457-1482: Add full sorting to open claims
  app/controllers/nsm/claims_controller.rb
  app/helpers/sortable_table_helper.rb
  app/services/prior_authority/sorter.rb
  app/services/sorter.rb
  app/view_models/nsm/v1/open_claims.rb
  app/views/nsm/claims/_open_table.html.erb
  app/views/nsm/claims/_table.html.erb
  app/views/nsm/claims/open.html.erb
  config/locales/en.yml
  config/locales/en/nsm/claims.yml
  config/locales/en/nsm/open_claims.yml
  spec/factories/claims.rb
  spec/system/nsm/view_claims_table_spec.rb
  spec/system/prior_authority/application_lists_spec.rb
  spec/system/prior_authority/view_related_applications_spec.rb
  spec/view_models/nsm/v1/open_claims_spec.rb
Labels: approved

#479 CRM457-1425: Make "Your claims" sortable
  app/controllers/nsm/claims_controller.rb
  app/services/sorter.rb
  app/view_models/nsm/v1/table_row.rb
  app/view_models/nsm/v1/your_claims.rb
  app/views/nsm/claims/_yours_table.html.erb
  app/views/nsm/claims/your.html.erb
  config/locales/en/nsm/claims.yml
  spec/view_models/nsm/v1/table_row_spec.rb
  spec/view_models/nsm/v1/your_claims_spec.rb
Labels: ready for review

#483 CRM457-1467: Use rationals instead of decimals to deal with recurring decimal imprecision
  app/view_models/nsm/v1/work_item.rb
  spec/view_models/nsm/v1/core_cost_summary_spec.rb
Labels: ready for review

#482 CRM457-1427: Sortable closed claims
  app/controllers/nsm/claims_controller.rb
  app/view_models/nsm/v1/assessed_claims.rb
  app/views/nsm/claims/_closed_table.html.erb
  app/views/nsm/claims/closed.html.erb
  spec/view_models/base_view_model_spec.rb
  spec/view_models/nsm/v1/assessed_claims_spec.rb
Labels: approved, In QA

#486 CRM457-1502: Show wasted costs if present
  app/view_models/nsm/v1/claim_details.rb
  config/locales/en/nsm/claim_details.yml
  spec/view_models/nsm/v1/claim_details_spec.rb
Labels: approved, In QA

#489 CRM457-1504: Fix priority logic
  app/services/prior_authority/choose_application_for_assignment.rb
  spec/services/prior_authority/choose_application_for_assignment_spec.rb
Labels: approved, In QA

#491 CRM457-1527: Prefer older claims
  app/controllers/nsm/claims_controller.rb
  spec/system/nsm/assignment_spec.rb
Labels: approved, In QA

#485 CRM457-1379: Full disbursement adjustments
  app/attributes/type/fully_validatable_decimal.rb
  app/controllers/nsm/disbursements_controller.rb
  app/forms/nsm/disbursements_form.rb
  app/javascript/application.js
  app/javascript/component/nsm/disbursement_adjustment.js
  app/view_models/nsm/v1/disbursement.rb
  app/views/nsm/disbursements/edit.html.erb
  config/initializers/attribute_types.rb
  config/locales/en/nsm/disbursements.yml
  spec/attributes/type/fully_validatable_decimal_spec.rb
  spec/forms/nsm/disbursements_form_spec.rb
  spec/system/nsm/disbursements_spec.rb
  spec/system/nsm/overview_spec.rb
  spec/view_models/nsm/v1/disbursement_spec.rb
Labels: approved, In QA

#492 Bump braces 3.0.2 to 3.0.3
  .snyk
  package.json
  yarn.lock
Labels: ready for review

#497 Add accessibility statement page
  app/controllers/about/accessibility_controller.rb
  app/views/about/accessibility/index.en.html.erb
  app/views/layouts/_footer_links.html.erb
  config/routes.rb
  spec/system/accessibility_statement_spec.rb
Labels: ready for review

#496 CRM457-1551: Amend "Get next" logic
  app/services/prior_authority/choose_application_for_assignment.rb
  spec/services/prior_authority/choose_application_for_assignment_spec.rb
Labels: ready for review

#501 [CMR457-1552] CRM4 Caseworker: content changes to RFI
  app/views/prior_authority/send_backs/new.html.erb
  config/locales/en/prior_authority/applications.yml
  config/locales/en/prior_authority/send_backs.yml
  spec/system/prior_authority/send_back_spec.rb
Labels: bug, ready for review
