Repository ministryofjustice/laa-assess-crime-forms, pull requests merged in 2024-10, with the labels that each got.

#791 CRM457-2096: Validate before submit and use realistic test data
  Gemfile
  Gemfile.lock
  app/services/notify_app_store/message_builder.rb
  spec/factories/prior_authority_applications.rb
  spec/forms/prior_authority/send_back_form_spec.rb
  spec/services/notify_app_store/message_builder_spec.rb
  spec/view_models/prior_authority/v1/application_details_spec.rb
Labels: approved

#794 Bump gem
  Gemfile
  Gemfile.lock
Labels: ready for review

#795 CRM457-2129: Validate NSM payloads
  Gemfile
  Gemfile.lock
  app/services/notify_app_store/message_builder.rb
  spec/services/notify_app_store/message_builder_spec.rb
Labels: approved, In QA

#796 bump gem
  Gemfile
  Gemfile.lock
Labels: approved

#797 CRM457-2049: Fix RFI/'delete all adjustments' edge case
  app/services/nsm/all_adjustments_deleter.rb
  spec/factories/claims.rb
  spec/services/nsm/adjustment_deleter_spec.rb
  spec/services/nsm/all_adjustments_deleter_spec.rb
  spec/system/nsm/adjustments_spec.rb
Labels: approved, In QA

#798 CRM457-2141: Handle custom other types
  app/view_models/nsm/v1/disbursement.rb
  spec/view_models/nsm/v1/disbursement_spec.rb
Labels: approved, In QA

#802 CRM457-2110: Change no data messaging
  Gemfile
  Gemfile.lock
  app/views/nsm/disbursements/_adjusted.html.erb
  app/views/nsm/disbursements/_index.html.erb
  config/locales/en/nsm/disbursements.yml
  config/locales/en/nsm/letters_and_calls.yml
  config/locales/en/nsm/work_items.yml
  spec/system/nsm/adjustments_spec.rb
Labels: approved, In QA

#793 [CRM457-2104] add service types to granted and part granted emails
  app/mailers/prior_authority/feedback_messages/feedback_base.rb
  app/mailers/prior_authority/feedback_messages/granted_feedback.rb
  app/mailers/prior_authority/feedback_messages/part_granted_feedback.rb
  spec/mailers/prior_authority/feedback_messages/granted_feedback_spec.rb
  spec/mailers/prior_authority/feedback_messages/part_granted_feedback_spec.rb
Labels: approved

#803 CRM457-2144: Dynamic page titles
  app/helpers/application_helper.rb
  app/views/layouts/nsm.html.erb
  config/locales/en.yml
  spec/helpers/application_helper_spec.rb
Labels: approved, In QA

#807 CRM457-2152: Remove false positive
  helm_deploy/templates/ingress.yaml
Labels: approved

#805 CRM457-2149: Don't override adjustment comments when removing all uplifts
  app/forms/base_adjustment_form.rb
  app/forms/nsm/uplift/base_form.rb
  app/forms/prior_authority/travel_cost_form.rb
  spec/forms/nsm/uplift/base_form_spec.rb
  spec/forms/nsm/work_item_form_spec.rb
Labels: approved, In QA

#804 CRM457-1987: QA feedback
  app/controllers/nsm/claim_details_controller.rb
  app/controllers/nsm/send_backs_controller.rb
  app/models/event/new_version.rb
  app/models/nsm/event/send_back.rb
  app/views/nsm/claim_details/show.html.erb
  app/views/nsm/send_backs/show.html.erb
  config/locales/en/events.yml
  config/locales/en/nsm/claim_details.yml
  config/locales/en/nsm/send_back.yml
  config/routes.rb
  spec/controllers/nsm/claim_details_controller_spec.rb
  spec/controllers/nsm/send_backs_controller_spec.rb
  spec/models/event/send_back_spec.rb
  spec/system/nsm/assessment_spec.rb
  spec/system/nsm/history_spec.rb
Labels: approved, In QA

#808 Enable NSM RFI on UAT
  config/feature_flags.yml
Labels: approved

#809 Enable NSM RFI on production
  config/feature_flags.yml
Labels: approved

#769 CRM7 Caseworker: Change defendant details design
  app/view_models/nsm/v1/defendant_details.rb
  config/locales/en/nsm/claim_details.yml
  spec/view_models/nsm/v1/defendant_details_spec.rb
Labels: approved, In QA

#810 CRM457-2095: Add flags indicating async job status
  app/models/event.rb
  app/services/notify_app_store.rb
  app/services/notify_event_app_store.rb
  db/migrate/20241015091931_add_notify_app_store_complete_to_submission.rb
  db/schema.rb
  spec/services/notify_app_store_spec.rb
  spec/services/notify_event_app_store_spec.rb
Labels: approved

#812 CRM457-2094: Make critical job enqueueings atomic
  app/forms/nsm/make_decision_form.rb
  app/forms/nsm/send_back_form.rb
  app/forms/prior_authority/decision_form.rb
  app/forms/prior_authority/send_back_form.rb
  app/models/event.rb
  app/models/event/new_version.rb
  app/services/notify_app_store.rb
  spec/models/event/new_version_spec.rb
  spec/services/notify_app_store_spec.rb
Labels: approved

#811 CRM457-2018: Migrate roles to a has-many relationship
  app/models/event.rb
  app/models/role.rb
  app/models/user.rb
  db/migrate/20241015110647_create_roles.rb
  db/schema.rb
  db/seeds/caseworkers.rb
  lib/tasks/custom_seeds.rake
  lib/tasks/user.rake
  spec/factories/role.rb
  spec/factories/users.rb
  spec/services/update_submission_spec.rb
Labels: approved

#817 CRM457-2098: Add PII annotations
  db/pii.yml
  spec/models/pii_spec.rb
Labels: approved

#820 CRM457-2183: Allow downloading of RFI files
  app/controllers/nsm/further_information_downloads_controller.rb
  app/view_models/nsm/v1/further_information.rb
  config/routes.rb
  spec/system/nsm/overview_spec.rb
  spec/view_models/nsm/v1/further_information_spec.rb
Labels: ready for review

#823 Updates accessibility statement
  app/views/about/accessibility/index.en.html.erb
Labels: approved

#825 CRM457-2061: Add licence link
  LICENCE
  README.md
Labels: ready for review
