Repository ministryofjustice/laa-assess-crime-forms, pull requests merged in 2024-02, with the labels that each got.

#287 CRM457-1062: Use Redis pods for temporary branches
  .circleci/config.yml
  config/initializers/sidekiq.rb
  helm_deploy/Chart.lock
  helm_deploy/Chart.yaml
  helm_deploy/charts/redis-17.15.2.tgz
  helm_deploy/templates/_helpers.tpl
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: approved

#297 CRM457-1168: Add PA standard header
  app/controllers/prior_authority/additional_costs_controller.rb
  app/controllers/prior_authority/applications_controller.rb
  app/forms/prior_authority/additional_cost_form.rb
  app/view_models/prior_authority/v1/additional_cost.rb
  app/view_models/prior_authority/v1/application_details.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/view_models/prior_authority/v1/quote.rb
  app/views/prior_authority/additional_costs/edit.html.erb
  app/views/prior_authority/adjustments/index.html.erb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/shared/_application_nav.html.erb
  app/views/prior_authority/shared/_sub_navigation.html.erb
  app/views/prior_authority/shared/_summary.html.erb
  config/environments/development.rb
  config/initializers/date_and_time_formats.rb
  config/locales/en.yml
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/applications.yml
  config/locales/en/prior_authority/service_types.yml
  spec/factories/prior_authority_applications.rb
  spec/system/prior_authority/view_applications_spec.rb
  spec/view_models/prior_authority/application_summary_spec.rb
Labels: approved

#302 CI: Add tests to merged pr flow
  .circleci/config.yml
Labels: approved

#306 CI: Add missing security context to values
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  helm_deploy/values-dev.yaml
  helm_deploy/values-prod.yaml
  helm_deploy/values-uat.yaml
Labels: ready for review

#309 Bump ruby 3.2.2 to 3.3.0
  .circleci/config.yml
  .rubocop.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
  README.md
Labels: approved

#313 CRM457-1103: Switch to propshaft
  .circleci/config.yml
  Gemfile
  Gemfile.lock
  Procfile.dev
  app/assets/config/manifest.js
  app/assets/stylesheets/local/govuk.scss
  app/javascript/application.js
  app/javascript/controllers/index.js
  app/views/layouts/govuk_template.html.erb
  bin/dev
  bin/importmap
  config/application.rb
  config/importmap.rb
  config/initializers/assets.rb
  config/initializers/dartsass.rb
  helm_deploy/templates/deployment.yaml
  package.json
  spec/system/errors_spec.rb
  yarn.lock
Labels: ready for review

#315 CRM457-1092: CSP
  app/views/layouts/_header_navigation.html.erb
  app/views/layouts/govuk_template.html.erb
  config/initializers/content_security_policy.rb
Labels: ready for review

#307 CRM457-1169: Add all the cards for the overview screen
  app/controllers/prior_authority/downloads_controller.rb
  app/view_models/prior_authority/v1/additional_cost.rb
  app/view_models/prior_authority/v1/application_details.rb
  app/view_models/prior_authority/v1/application_details/alternative_quote_card.rb
  app/view_models/prior_authority/v1/application_details/base_card.rb
  app/view_models/prior_authority/v1/application_details/case_contact_card.rb
  app/view_models/prior_authority/v1/application_details/case_details_card.rb
  app/view_models/prior_authority/v1/application_details/client_details_card.rb
  app/view_models/prior_authority/v1/application_details/hearing_details_card.rb
  app/view_models/prior_authority/v1/application_details/next_hearing_card.rb
  app/view_models/prior_authority/v1/application_details/no_alternative_quotes_card.rb
  app/view_models/prior_authority/v1/application_details/overview_card.rb
  app/view_models/prior_authority/v1/application_details/primary_quote_card.rb
  app/view_models/prior_authority/v1/application_details/reason_why_card.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/view_models/prior_authority/v1/document.rb
  app/view_models/prior_authority/v1/quote.rb
  app/views/prior_authority/applications/_alternative_quote_card.html.erb
  app/views/prior_authority/applications/_case_contact_card.html.erb
  app/views/prior_authority/applications/_case_details_card.html.erb
  app/views/prior_authority/applications/_client_details_card.html.erb
  app/views/prior_authority/applications/_hearing_details_card.html.erb
  app/views/prior_authority/applications/_next_hearing_card.html.erb
  app/views/prior_authority/applications/_no_alternative_quotes_card.html.erb
  app/views/prior_authority/applications/_overview_card.html.erb
  app/views/prior_authority/applications/_primary_quote_card.html.erb
  app/views/prior_authority/applications/_reason_why_card.html.erb
  app/views/prior_authority/applications/show.html.erb
  config/locales/en/prior_authority/applications.yml
  config/routes.rb
  spec/factories/prior_authority_applications.rb
  spec/support/shared_examples/shared_claim_feedback_mailer.rb
  spec/system/prior_authority/view_applications_spec.rb
  spec/view_models/prior_authority/v1/additional_cost_spec.rb
  spec/view_models/prior_authority/v1/application_details_spec.rb
  spec/view_models/prior_authority/v1/application_summary_spec.rb
Labels: approved, In QA

#317 CRM457 1115: Add quote adjustment tab
  Gemfile
  Gemfile.lock
  app/controllers/prior_authority/adjustments_controller.rb
  app/view_models/prior_authority/v1/additional_cost.rb
  app/view_models/prior_authority/v1/application_details/key_information_card.rb
  app/view_models/prior_authority/v1/application_details/primary_quote_card.rb
  app/view_models/prior_authority/v1/key_information.rb
  app/view_models/prior_authority/v1/quote.rb
  app/views/prior_authority/adjustments/_additional_costs.html.erb
  app/views/prior_authority/adjustments/_key_information_card.html.erb
  app/views/prior_authority/adjustments/_service_costs.html.erb
  app/views/prior_authority/adjustments/_travel_costs.erb
  app/views/prior_authority/adjustments/index.html.erb
  app/views/prior_authority/shared/_application_nav.html.erb
  config/environments/development.rb
  config/locales/en.yml
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/adjustments.yml
  config/locales/en/prior_authority/application_details.yml
  config/locales/en/prior_authority/applications.yml
  doc/adjustments.md
  spec/factories/prior_authority_applications.rb
  spec/system/prior_authority/view_adjust_quote_spec.rb
  spec/view_models/prior_authority/v1/additional_cost_spec.rb
  spec/view_models/prior_authority/v1/application_details/key_information_card_spec.rb
  spec/view_models/prior_authority/v1/key_information_spec.rb
  spec/view_models/prior_authority/v1/quote_spec.rb
Labels: ready for review

#312 Document and add env vars required for local e2e development
  .env.development
  Procfile.dev
  README.md
Labels: approved
