Repository ministryofjustice/laa-assess-crime-forms, pull requests merged in 2024-07, with the labels that each got.

#590 CRM457-1319: Swallow team-only notification client errors on DEV/UAT
  app/mailers/notify_mailer.rb
  app/mailers/nsm/submission_feedback_mailer.rb
  app/mailers/prior_authority/submission_feedback_mailer.rb
  spec/mailers/nsm/submission_feedback_mailer_spec.rb
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
  spec/support/shared_examples/shared_claim_feedback_mailer.rb
Labels: ready for review

#592 CRM457-1706: Change out of hours schedule for ExpireSendbacks job
  config/schedule.yml
Labels: approved

#583 CRM457-1678: Show comment on overview page for assessed claims
  app/view_models/nsm/v1/claim_summary.rb
  app/views/nsm/claim_details/show.html.erb
  config/locales/en/nsm/claim_details.yml
  spec/system/nsm/assessment_spec.rb
Labels: approved, In QA

#593 Configure sidekiq to use specific database locally
  config/initializers/sidekiq.rb
Labels: approved

#597 CRM457 -1714: Better dummy data
  app/jobs/nsm/fake_assess.rb
  app/jobs/prior_authority/fake_assess.rb
  lib/tasks/dummy_assessments.rake
  spec/jobs/nsm/fake_assess_spec.rb
  spec/jobs/prior_authority/fake_assess_spec.rb
Labels: ready for review

#596 CRM457-1529: Change snyk docker scanning approach
  .circleci/config.yml
  app/controllers/nsm/assignments_controller.rb
  app/controllers/prior_authority/manual_assignments_controller.rb
  app/controllers/prior_authority/unassignments_controller.rb
  app/views/nsm/assignments/new.html.erb
  app/views/prior_authority/manual_assignments/new.html.erb
  app/views/prior_authority/unassignments/new.html.erb
Labels: approved

#599 CMR457-1724: Use snyk to test IaC/helm templates
  .circleci/config.yml
  helm_deploy/templates/tests/test-connection.yaml
Labels: approved

#602 CRM457-1672: Concurrent migrations
  lib/tasks/db.rake
  run.sh
Labels: approved

#603 CRM457-1660: Use internal hostname to bypass modsec
  .env.development
  app/services/app_store_subscriber.rb
  config/environments/production.rb
  helm_deploy/templates/_helpers.tpl
  helm_deploy/templates/deployment.yaml
  spec/services/app_store_subscriber_spec.rb
Labels: approved

#608 Get dependabot to update docker dependencies
  .github/dependabot.yml
Labels: approved

#604 Crm457 1697/work completed date
  .rubocop.yml
  app/view_models/nsm/v1/claim_details.rb
  config/locales/en/nsm/claim_details.yml
  spec/factories/claims.rb
  spec/view_models/nsm/v1/claim_details_spec.rb
Labels: approved

#613 Crm457 1731/other details
  app/view_models/nsm/v1/claim_justification.rb
  config/locales/en/nsm/claim_details.yml
  spec/view_models/nsm/v1/claim_justification_spec.rb
Labels: approved

#601 CRM457-1726: Swallow event sync errors if they are redundant
  app/services/app_store_client.rb
  app/services/notify_event_app_store.rb
  spec/services/notify_event_app_store_spec.rb
Labels: ready for review

#614 CRM457-1368: Unsub from app store on branch deletion
  .github/actions/delete-dev-release/action.yml
  app/services/app_store_client.rb
  app/services/app_store_subscriber.rb
  config/application.rb
  lib/tasks/app_store.rake
  spec/lib/tasks/app_store_unsubscribe_spec.rb
  spec/services/app_store_client_spec.rb
  spec/services/app_store_subscriber_spec.rb
Labels: approved

#615 CRM457-1744: Fix for non-iso chars
  app/controllers/prior_authority/downloads_controller.rb
  spec/system/prior_authority/view_applications_spec.rb
Labels: ready for review

#612 CRM457-1736: Remove provider requested option
  app/controllers/nsm/send_backs_controller.rb
  app/forms/nsm/send_back_form.rb
  app/helpers/submission_tag_helper.rb
  app/jobs/nsm/fake_assess.rb
  app/mailers/nsm/feedback_messages/provider_request_feedback.rb
  app/mailers/nsm/submission_feedback_mailer.rb
  app/models/claim.rb
  app/views/nsm/send_backs/edit.html.erb
  config/locales/en.yml
  config/locales/en/events.yml
  config/locales/en/nsm/send_back.yml
  config/locales/en/nsm/your_claims.yml
  spec/controllers/nsm/send_backs_controller_spec.rb
  spec/forms/nsm/send_back_form_spec.rb
  spec/jobs/nsm/fake_assess_spec.rb
  spec/mailers/nsm/feedback_messages/provider_request_feedback_spec.rb
  spec/mailers/nsm/submission_feedback_mailer_spec.rb
  spec/models/event/send_back_spec.rb
  spec/system/nsm/assessment_spec.rb
Labels: approved, In QA

#616 CRM457-1744: Extend character protection to NSM downloads
  app/controllers/concerns/file_redirectable.rb
  app/controllers/nsm/downloads_controller.rb
  app/controllers/prior_authority/downloads_controller.rb
Labels: approved

#617 CRM457-1749: Sending back a claim removes assignments
  app/forms/nsm/send_back_form.rb
  spec/forms/nsm/send_back_form_spec.rb
Labels: approved, In QA

#620 CRM457-1721: More modsec false positives
  helm_deploy/templates/ingress.yaml
Labels: ready for review

#589 Provider: Analytics Dashboard Tab (CRM4 & CRM7)
  app/controllers/dashboards_controller.rb
  app/views/dashboards/_autogrant.html.erb
  app/views/dashboards/_caseworkers.html.erb
  app/views/dashboards/_nsm_nav.html.erb
  app/views/dashboards/_prior_authority_nav.html.erb
  app/views/dashboards/_search.html.erb
  app/views/dashboards/_tab_content.html.erb
  app/views/dashboards/show.html.erb
  app/views/home/index.html.erb
  app/views/layouts/_header_navigation.html.erb
  app/views/layouts/dashboard/_primary_navigation.html.erb
  config/locales/en.yml
  config/locales/en/assess_a_crime_form.yml
  config/locales/en/dashboards.yml
  helm_deploy/values-dev.yaml
  spec/controllers/dashboard_controller_spec.rb
  spec/system/dashboards_spec.rb
Labels: approved

#625 CRM457-1754: Fix button styling
  app/views/shared/_claim_button_group.erb
  config/locales/en.yml
Labels: approved, In QA

#629 Pull latest AWS RDS certs
  Dockerfile
Labels: ready for review

#631 CRM457-1361: Swap PII for caseworker ID in logs
  Gemfile
  Gemfile.lock
  config/initializers/filter_parameter_logging.rb
  config/initializers/lograge.rb
Labels: approved

#636 Enable search in production
  config/feature_flags.yml
Labels: ready for review

#646 CRM457-1790: Discard all adjustments prior to sending back
  app/forms/prior_authority/send_back_form.rb
  spec/forms/prior_authority/send_back_form_spec.rb
  spec/jobs/prior_authority/fake_assess_spec.rb
  spec/services/sorters/work_items_sorter_spec.rb
  spec/system/prior_authority/send_back_spec.rb
Labels: approved, In QA

#643 Analytics Search: Add correct params when sorting results table
  app/helpers/sortable_table_helper.rb
  app/views/dashboards/_tab_content.html.erb
  app/views/shared/_search.html.erb
  spec/system/dashboards_spec.rb
Labels: approved
