Repository ministryofjustice/laa-assess-crime-forms, pull requests merged in 2024-03, with the labels that each got.

#318 CRM457-992: Change format period inline with prototype designs
  config/locales/en/helpers.yml
  spec/helpers/application_helper_spec.rb
  spec/system/nsm/work_items_spec.rb
  spec/system/prior_authority/adjustments_spec.rb
  spec/system/prior_authority/view_adjust_quote_spec.rb
  spec/view_models/nsm/v1/claim_details_spec.rb
  spec/view_models/nsm/v1/travel_and_waiting_spec.rb
  spec/view_models/nsm/v1/work_item_spec.rb
  spec/view_models/prior_authority/v1/additional_cost_spec.rb
Labels: approved

#320 CRM457-1151: Preserve original values in payload
  app/forms/base_adjustment_form.rb
  app/forms/nsm/disbursements_form.rb
  app/forms/nsm/letters_calls_form.rb
  app/forms/nsm/work_item_form.rb
  app/lib/cost_calculator.rb
  app/view_models/base_view_model.rb
  app/view_models/base_with_adjustments.rb
  app/view_models/nsm/v1/core_cost_summary.rb
  app/view_models/nsm/v1/disbursement.rb
  app/view_models/nsm/v1/letter_and_call.rb
  app/view_models/nsm/v1/letters_and_calls_summary.rb
  app/view_models/nsm/v1/work_item.rb
  app/view_models/nsm/v1/work_item_summary.rb
  app/view_models/prior_authority/v1/additional_cost.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/view_models/prior_authority/v1/quote.rb
  app/views/nsm/disbursements/show.html.erb
  app/views/nsm/letters_and_calls/show.html.erb
  app/views/nsm/work_items/show.html.erb
  app/views/prior_authority/shared/_application_nav.html.erb
  config/locales/en/prior_authority.yml
  spec/controllers/nsm/disbursements_controller_spec.rb
  spec/forms/nsm/disbursements_form_spec.rb
  spec/forms/nsm/letters_calls_form_spec.rb
  spec/forms/nsm/work_item_form_spec.rb
  spec/lib/cost_calculator_spec.rb
  spec/system/prior_authority/adjustments_spec.rb
  spec/view_models/base_view_model_spec.rb
  spec/view_models/nsm/v1/core_cost_summary_spec.rb
  spec/view_models/nsm/v1/disbursement_spec.rb
  spec/view_models/nsm/v1/letter_and_call_spec.rb
  spec/view_models/nsm/v1/letters_and_calls_summary_spec.rb
  spec/view_models/nsm/v1/travel_and_waiting_spec.rb
  spec/view_models/nsm/v1/work_item_spec.rb
Labels: approved

#322 Bump AWS orbs
  .circleci/config.yml
Labels: ready for review

#323 CRM457-1112: Remove authentication when not applicable
  .env.test
  app/services/app_store_token_provider.rb
  app/services/http_puller.rb
  app/services/notify_app_store/http_notifier.rb
  spec/services/app_store_token_provider_spec.rb
  spec/services/http_puller_spec.rb
  spec/services/notify_app_store/http_notifier_spec.rb
Labels: ready for review

#325 Get NSM JS working again
  app/javascript/component/letters_calls_adjustment.js
  app/javascript/component/work_item_adjustment.js
  config/locales/en/nsm/disbursements.yml
Labels: approved

#319 CRM457-1041: Offence and prison lists
  app/view_models/prior_authority/v1/additional_cost.rb
  app/view_models/prior_authority/v1/application_details.rb
  app/view_models/prior_authority/v1/application_details/case_details_card.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/view_models/prior_authority/v1/key_information.rb
  app/view_models/prior_authority/v1/quote.rb
  app/views/prior_authority/applications/_primary_quote_card.html.erb
  app/views/prior_authority/applications/show.html.erb
  config/locales/en/prior_authority/application_details.yml
  config/locales/en/prior_authority/offences.yml
  config/locales/en/prior_authority/prisons.yml
  db/migrate/20240307154917_update_data_blobs.rb
  db/schema.rb
  spec/factories/prior_authority_applications.rb
  spec/system/accessibility_spec.rb
  spec/system/prior_authority/view_adjust_quote_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
  spec/view_models/prior_authority/v1/application_details/key_information_card_spec.rb
  spec/view_models/prior_authority/v1/application_details_spec.rb
  spec/view_models/prior_authority/v1/application_summary_spec.rb
  spec/view_models/prior_authority/v1/key_information_spec.rb
  spec/view_models/prior_authority/v1/quote_spec.rb
Labels: approved

#330 CRM457-1114: Add additional costs form
  app/forms/prior_authority/additional_cost_form.rb
  app/forms/prior_authority/base_cost_adjustment_form.rb
  app/forms/prior_authority/service_cost_form.rb
  app/javascript/application.js
  app/javascript/component/prior_authority/additional_cost_adjustment.js
  app/javascript/component/prior_authority/cost_adjustment.js
  app/javascript/component/prior_authority/service_cost_adjustment.js
  app/view_models/prior_authority/additional_costs_with_adjustments.rb
  app/view_models/prior_authority/v1/additional_cost.rb
  app/view_models/prior_authority/v1/quote.rb
  app/views/prior_authority/additional_costs/_cost_fields.html.erb
  app/views/prior_authority/additional_costs/edit.html.erb
  app/views/prior_authority/adjustments/_additional_costs.html.erb
  config/locales/en/prior_authority/additional_costs.yml
  spec/system/prior_authority/adjust_additional_costs_spec.rb
  spec/system/prior_authority/view_adjust_quote_spec.rb
  spec/view_models/prior_authority/v1/additional_cost_spec.rb
Labels: ready for review

#334 CRM457-1114: update overview to show original values
  app/view_models/prior_authority/v1/additional_cost.rb
  app/view_models/prior_authority/v1/application_details/alternative_quote_card.rb
  app/view_models/prior_authority/v1/application_details/primary_quote_card.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/view_models/prior_authority/v1/quote.rb
  spec/system/prior_authority/view_applications_spec.rb
  spec/view_models/prior_authority/v1/additional_cost_spec.rb
Labels: approved

#336 Extract coverage to separate job and collate
  .circleci/config.yml
  Gemfile
  lib/tasks/simplecov/process_coverage.rake
  spec/rails_helper.rb
  spec/services/app_store_token_provider_spec.rb
  spec/spec_helper.rb
Labels: approved

#339 Amend PR template
  .github/pull_request_template.md
Labels: approved

#338 CRM457-1114: Do not display calculated adjustments on page load
  app/javascript/component/prior_authority/additional_cost_adjustment.js
  app/javascript/component/prior_authority/service_cost_adjustment.js
  app/javascript/component/prior_authority/travel_cost_adjustment.js
  app/views/prior_authority/additional_costs/edit.html.erb
  app/views/prior_authority/service_costs/edit.html.erb
  app/views/prior_authority/travel_costs/edit.html.erb
  config/locales/en/prior_authority/additional_costs.yml
  config/locales/en/prior_authority/service_costs.yml
  config/locales/en/prior_authority/travel_costs.yml
  spec/system/prior_authority/adjust_additional_costs_spec.rb
  spec/system/prior_authority/adjust_service_costs_spec.rb
  spec/system/prior_authority/adjust_travel_costs_spec.rb
Labels: approved

#337 CRM457-997: Manual assignment and unassignment
  app/controllers/prior_authority/applications_controller.rb
  app/controllers/prior_authority/assignments_controller.rb
  app/controllers/prior_authority/auto_assignments_controller.rb
  app/controllers/prior_authority/manual_assignments_controller.rb
  app/controllers/prior_authority/unassignments_controller.rb
  app/forms/prior_authority/manual_assignment_form.rb
  app/forms/prior_authority/unassignment_form.rb
  app/helpers/sortable_table_helper.rb
  app/models/event/assignment.rb
  app/services/prior_authority/sorter.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/view_models/prior_authority/v1/table_row.rb
  app/views/prior_authority/applications/your.html.erb
  app/views/prior_authority/manual_assignments/new.html.erb
  app/views/prior_authority/shared/_application_nav.html.erb
  app/views/prior_authority/unassignments/new.html.erb
  app/views/shared/_pagination.html.erb
  app/views/shared/_pagination_info.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/manual_assignments.yml
  config/locales/en/prior_authority/unassignments.yml
  config/routes.rb
  spec/system/prior_authority/adjust_additional_costs_spec.rb
  spec/system/prior_authority/adjust_service_costs_spec.rb
  spec/system/prior_authority/adjust_travel_costs_spec.rb
  spec/system/prior_authority/adjustments_spec.rb
  spec/system/prior_authority/application_lists_spec.rb
  spec/system/prior_authority/assign_applications_spec.rb
  spec/system/prior_authority/view_adjust_quote_spec.rb
Labels: approved, In QA

#348 CRM457-1218: Add location service to check if postcode inside M25
  .circleci/config.yml
  .env.development
  .env.test
  Brewfile
  Gemfile
  Gemfile.lock
  README.md
  app/services/location_service.rb
  app/services/location_service/M25.kml
  config/database.yml
  db/migrate/20240313123836_add_postgis_extension_to_database.rb
  db/schema.rb
  helm_deploy/templates/deployment-worker.yaml
  helm_deploy/templates/deployment.yaml
  spec/services/location_service_spec.rb
Labels: approved

#347 CRM457-992: Add item cost error messages
  app/forms/prior_authority/base_cost_adjustment_form.rb
  app/validators/item_type_dependant_validator.rb
  config/locales/en/errors.yml
  spec/system/prior_authority/adjust_service_costs_spec.rb
  spec/validators/item_type_dependant_validator_spec.rb
Labels: approved

#351 remove space
  config/locales/en/errors.yml
Labels: approved

#352 Update Github K8S Secrets
  .github/workflows/delete-dev-release.yml
Labels: approved

#354 Move docker image scan to run in parrallel to tests
  .circleci/config.yml
Labels: ready for review

#326 CRM457-1101: Make decision
  .env.development
  app/assets/stylesheets/application.scss
  app/assets/stylesheets/custom/govuk-button-group.scss
  app/controllers/prior_authority/decisions_controller.rb
  app/forms/prior_authority/decision_form.rb
  app/models/event.rb
  app/models/submission.rb
  app/view_models/prior_authority/v1/decision.rb
  app/views/prior_authority/adjustments/index.html.erb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/decisions/new.html.erb
  app/views/prior_authority/decisions/show.html.erb
  app/views/prior_authority/related_applications/index.html.erb
  config/locales/en/prior_authority/decisions.yml
  config/routes.rb
  spec/forms/prior_authority/decision_form_spec.rb
  spec/system/prior_authority/make_decision_spec.rb
Labels: approved, In QA

#350 CRM457-1005: Prior authority application history
  app/controllers/prior_authority/events_controller.rb
  app/forms/prior_authority/decision_form.rb
  app/models/event.rb
  app/models/event/draft_decision.rb
  app/view_models/prior_authority/v1/event_summary.rb
  app/views/prior_authority/events/index.html.erb
  app/views/prior_authority/shared/_application_nav.html.erb
  config/initializers/date_and_time_formats.rb
  config/locales/en/prior_authority/events.yml
  config/routes.rb
  spec/system/prior_authority/history_spec.rb
  spec/view_models/prior_authority/v1/event_summary_spec.rb
Labels: approved

#353 CRM457-976/980: Namespace mailers and wire up prior authority templates
  app/controllers/about/feedback_controller.rb
  app/mailers/feedback_messages/feedback_base.rb
  app/mailers/feedback_messages/further_information_request_feedback.rb
  app/mailers/feedback_messages/granted_feedback.rb
  app/mailers/feedback_messages/part_granted_feedback.rb
  app/mailers/feedback_messages/provider_request_feedback.rb
  app/mailers/feedback_messages/rejected_feedback.rb
  app/mailers/nsm/feedback_messages/feedback_base.rb
  app/mailers/nsm/feedback_messages/further_information_request_feedback.rb
  app/mailers/nsm/feedback_messages/granted_feedback.rb
  app/mailers/nsm/feedback_messages/part_granted_feedback.rb
  app/mailers/nsm/feedback_messages/provider_request_feedback.rb
  app/mailers/nsm/feedback_messages/rejected_feedback.rb
  app/mailers/nsm/submission_feedback_mailer.rb
  app/mailers/prior_authority/feedback_messages/feedback_base.rb
  app/mailers/prior_authority/feedback_messages/further_information_request_feedback.rb
  app/mailers/prior_authority/feedback_messages/granted_feedback.rb
  app/mailers/prior_authority/feedback_messages/part_granted_feedback.rb
  app/mailers/prior_authority/feedback_messages/rejected_feedback.rb
  app/mailers/prior_authority/submission_feedback_mailer.rb
  app/mailers/submission_feedback_mailer.rb
  app/services/notify_app_store.rb
  app/view_models/prior_authority/v1/decision.rb
  spec/factories/prior_authority_applications.rb
  spec/mailers/nsm/feedback_messages/feedback_base_spec.rb
  spec/mailers/nsm/feedback_messages/further_information_request_feeback_spec.rb
  spec/mailers/nsm/feedback_messages/granted_feedback_spec.rb
  spec/mailers/nsm/feedback_messages/part_granted_feedback_spec.rb
  spec/mailers/nsm/feedback_messages/provider_request_feedback_spec.rb
  spec/mailers/nsm/feedback_messages/rejected_feedback_spec.rb
  spec/mailers/nsm/submission_feedback_mailer_spec.rb
  spec/mailers/prior_authority/feedback_messages/feedback_base_spec.rb
  spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb
  spec/mailers/prior_authority/feedback_messages/granted_feedback_spec.rb
  spec/mailers/prior_authority/feedback_messages/part_granted_feedback_spec.rb
  spec/mailers/prior_authority/feedback_messages/rejected_feedback_spec.rb
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
  spec/services/notify_app_store_spec.rb
  spec/support/shared_examples/shared_claim_feedback_mailer.rb
Labels: approved

#349 CRM457-1216: New service start page
  app/assets/stylesheets/custom/govuk-heading.scss
  app/controllers/application_controller.rb
  app/controllers/errors_controller.rb
  app/controllers/home_controller.rb
  app/controllers/nsm/landing_controller.rb
  app/controllers/prior_authority/static_pages_controller.rb
  app/controllers/users/omniauth_callbacks_controller.rb
  app/lib/omni_auth/strategies/dev_auth.rb
  app/views/errors/forbidden.html.erb
  app/views/home/index.html.erb
  app/views/layouts/_header_navigation.html.erb
  app/views/layouts/_primary_navigation.html.erb
  app/views/layouts/assess_a_crime_form.html.erb
  app/views/layouts/external.html.erb
  app/views/nsm/landing/index.html.erb
  app/views/prior_authority/static_pages/landing.html.erb
  app/views/users/dev_auth/new.html.erb
  config/application.rb
  config/locales/en/assess_a_crime_form.yml
  config/locales/en/errors.yml
  config/locales/en/nsm/landing.yml
  config/locales/en/prior_authority.yml
  config/routes.rb
  spec/controllers/nsm/landing_controller_spec.rb
  spec/system/accessibility_spec.rb
  spec/system/authenticating/dev_auth_spec.rb
  spec/system/authenticating/sign_out_spec.rb
  spec/system/nsm/risk_spec.rb
  spec/system/prior_authority/adjust_additional_costs_spec.rb
  spec/system/prior_authority/adjust_service_costs_spec.rb
  spec/system/prior_authority/adjust_travel_costs_spec.rb
  spec/system/prior_authority/assign_applications_spec.rb
  spec/system/prior_authority/view_adjust_quote_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
  spec/system/prior_authority/view_related_applications_spec.rb
Labels: approved

#358 CRM457-993: QA changes
  app/views/prior_authority/related_applications/index.html.erb
  spec/system/prior_authority/view_related_applications_spec.rb
Labels: approved

#355 CRM457-1185: Add 'Send back to provider' form
  app/controllers/prior_authority/send_backs_controller.rb
  app/forms/prior_authority/decision_form.rb
  app/forms/prior_authority/send_back_form.rb
  app/models/claim.rb
  app/models/event.rb
  app/models/event/draft_send_back.rb
  app/models/prior_authority_application.rb
  app/models/submission.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/view_models/prior_authority/v1/event_summary.rb
  app/view_models/prior_authority/v1/send_back.rb
  app/views/prior_authority/additional_costs/edit.html.erb
  app/views/prior_authority/adjustments/index.html.erb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/decisions/new.html.erb
  app/views/prior_authority/decisions/show.html.erb
  app/views/prior_authority/events/index.html.erb
  app/views/prior_authority/related_applications/index.html.erb
  app/views/prior_authority/send_backs/new.html.erb
  app/views/prior_authority/send_backs/show.html.erb
  app/views/prior_authority/service_costs/edit.html.erb
  app/views/prior_authority/shared/_application_buttons.html.erb
  app/views/prior_authority/travel_costs/edit.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/applications.yml
  config/locales/en/prior_authority/events.yml
  config/locales/en/prior_authority/related_applications.yml
  config/locales/en/prior_authority/send_backs.yml
  config/routes.rb
  spec/forms/prior_authority/send_back_form_spec.rb
  spec/system/prior_authority/history_spec.rb
  spec/system/prior_authority/send_back_spec.rb
Labels: ready for review

#359 CRM457-992: Correct expected behaviour of `items` field for adjustments
  app/attributes/type/fully_validatable_integer.rb
  app/forms/prior_authority/base_cost_adjustment_form.rb
  app/views/prior_authority/additional_costs/_cost_fields.html.erb
  app/views/prior_authority/service_costs/_cost_fields.html.erb
  config/initializers/attribute_types.rb
  spec/attributes/type/fully_validatable_integer_spec.rb
  spec/system/prior_authority/adjust_additional_costs_spec.rb
  spec/system/prior_authority/adjust_service_costs_spec.rb
Labels: approved

#363 CRM457-993: correct no records content para
  app/views/prior_authority/applications/assessed.html.erb
  app/views/prior_authority/applications/open.html.erb
  app/views/prior_authority/applications/your.html.erb
  app/views/prior_authority/related_applications/index.html.erb
Labels: ready for review

#366 CRM457-1186: Add resubmission deadline
  app/forms/prior_authority/send_back_form.rb
  config/application.rb
  spec/forms/prior_authority/send_back_form_spec.rb
Labels: approved

#365 CRM457-980: Add caseworker comments to further info request mailer
  app/mailers/prior_authority/feedback_messages/further_information_request_feedback.rb
  app/mailers/prior_authority/submission_feedback_mailer.rb
  app/models/event.rb
  spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
Labels: approved

#374 Minimise use of Rails.env
  .env.development
  .env.test
  app/controllers/concerns/cookie_concern.rb
  config/initializers/aws.rb
  config/initializers/sidekiq.rb
Labels: approved

#361 CRM457-994: Tweak application show page for different states
  app/helpers/prior_authority_tag_helper.rb
  app/view_models/prior_authority/v1/application_details.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/view_models/prior_authority/v1/table_row.rb
  app/views/prior_authority/adjustments/index.html.erb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/shared/_application_nav.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/adjustments.yml
  config/locales/en/prior_authority/applications.yml
  spec/system/prior_authority/view_applications_spec.rb
Labels: approved, In QA

#371 CRM457-1187: Tidy states and UI for showing sent back applications
  app/controllers/prior_authority/applications_controller.rb
  app/forms/prior_authority/decision_form.rb
  app/forms/prior_authority/send_back_form.rb
  app/models/claim.rb
  app/models/prior_authority_application.rb
  app/models/submission.rb
  app/services/prior_authority/choose_application_for_assignment.rb
  app/view_models/prior_authority/v1/application_details.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/shared/_application_nav.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/applications.yml
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
  spec/system/prior_authority/view_applications_spec.rb
  spec/system/prior_authority/view_related_applications_spec.rb
Labels: approved

#375 Update domain dev
  helm_deploy/values-dev.yaml
Labels: approved

#376 CRM457-976: Correct recipient for decision/RFI notifications
  app/mailers/prior_authority/feedback_messages/feedback_base.rb
  spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb
  spec/mailers/prior_authority/feedback_messages/granted_feedback_spec.rb
  spec/mailers/prior_authority/feedback_messages/part_granted_feedback_spec.rb
  spec/mailers/prior_authority/feedback_messages/rejected_feedback_spec.rb
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
  spec/support/shared_examples/shared_claim_feedback_mailer.rb
Labels: approved

#377 Do not inline sidekiq for bin/dev
  Procfile.dev
Labels: ready for review

#379 CRM457-1044: Make name handling more flexible
  app/controllers/nsm/send_backs_controller.rb
  app/mailers/nsm/feedback_messages/feedback_base.rb
  app/models/concerns/name_constructable.rb
  app/view_models/base_view_model.rb
  app/view_models/nsm/v1/all_claims.rb
  app/view_models/nsm/v1/assessed_claims.rb
  app/view_models/nsm/v1/claim_summary.rb
  app/view_models/nsm/v1/contact_details.rb
  app/view_models/nsm/v1/defendant_details.rb
  app/view_models/nsm/v1/your_claims.rb
  app/views/nsm/claims/_claim_summary.html.erb
  db/seeds/de2d6169-c769-4571-b3f2-220bcf8c3ce9/version.json
  db/seeds/f1ba0909-020f-4373-a167-9100923bdcaa/version.json
  spec/factories/claims.rb
  spec/view_models/nsm/v1/all_claims_spec.rb
  spec/view_models/nsm/v1/assessed_claims_spec.rb
  spec/view_models/nsm/v1/claim_summary_spec.rb
  spec/view_models/nsm/v1/defendant_details_spec.rb
  spec/view_models/nsm/v1/your_claims_spec.rb
Labels: approved

#383 CRM457-1033: Remove feedback URL from all notifications
  app/mailers/nsm/feedback_messages/feedback_base.rb
  app/mailers/nsm/feedback_messages/further_information_request_feedback.rb
  app/mailers/nsm/feedback_messages/granted_feedback.rb
  app/mailers/nsm/feedback_messages/part_granted_feedback.rb
  app/mailers/nsm/feedback_messages/provider_request_feedback.rb
  app/mailers/nsm/feedback_messages/rejected_feedback.rb
  app/mailers/prior_authority/feedback_messages/feedback_base.rb
  app/mailers/prior_authority/feedback_messages/further_information_request_feedback.rb
  app/mailers/prior_authority/feedback_messages/granted_feedback.rb
  app/mailers/prior_authority/feedback_messages/part_granted_feedback.rb
  app/mailers/prior_authority/feedback_messages/rejected_feedback.rb
  spec/mailers/nsm/feedback_messages/further_information_request_feeback_spec.rb
  spec/mailers/nsm/feedback_messages/granted_feedback_spec.rb
  spec/mailers/nsm/feedback_messages/part_granted_feedback_spec.rb
  spec/mailers/nsm/feedback_messages/provider_request_feedback_spec.rb
  spec/mailers/nsm/feedback_messages/rejected_feedback_spec.rb
  spec/mailers/nsm/submission_feedback_mailer_spec.rb
  spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb
  spec/mailers/prior_authority/feedback_messages/granted_feedback_spec.rb
  spec/mailers/prior_authority/feedback_messages/part_granted_feedback_spec.rb
  spec/mailers/prior_authority/feedback_messages/rejected_feedback_spec.rb
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
Labels: approved

#384 Update domain dev
  helm_deploy/values-dev.yaml
Labels: approved

#381 CRM457-1195: Adjust expired application UI
  app/controllers/prior_authority/applications_controller.rb
  app/controllers/prior_authority/related_applications_controller.rb
  app/models/prior_authority_application.rb
  app/services/prior_authority/sorter.rb
  app/view_models/prior_authority/v1/table_row.rb
  app/views/layouts/prior_authority/_primary_navigation.html.erb
  app/views/prior_authority/applications/closed.html.erb
  app/views/prior_authority/applications/open.html.erb
  app/views/prior_authority/applications/your.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/applications.yml
  config/routes.rb
  spec/system/prior_authority/application_lists_spec.rb
  spec/system/prior_authority/view_related_applications_spec.rb
Labels: ready for review

#380 CRM457-1195: Expire old send-backs
  app/controllers/prior_authority/applications_controller.rb
  app/controllers/prior_authority/related_applications_controller.rb
  app/helpers/prior_authority_tag_helper.rb
  app/jobs/expire_sendbacks.rb
  app/models/event.rb
  app/models/event/expiry.rb
  app/models/prior_authority_application.rb
  app/services/notify_app_store.rb
  app/services/prior_authority/sorter.rb
  app/view_models/prior_authority/v1/application_summary.rb
  app/view_models/prior_authority/v1/event_summary.rb
  app/view_models/prior_authority/v1/table_row.rb
  app/views/layouts/prior_authority/_primary_navigation.html.erb
  app/views/prior_authority/applications/closed.html.erb
  app/views/prior_authority/applications/open.html.erb
  app/views/prior_authority/applications/show.html.erb
  app/views/prior_authority/applications/your.html.erb
  app/views/prior_authority/shared/_application_nav.html.erb
  config/locales/en/prior_authority.yml
  config/locales/en/prior_authority/applications.yml
  config/locales/en/prior_authority/events.yml
  config/routes.rb
  config/schedule.yml
  spec/jobs/expire_sendbacks_spec.rb
  spec/services/notify_app_store_spec.rb
  spec/system/prior_authority/application_lists_spec.rb
  spec/system/prior_authority/view_related_applications_spec.rb
Labels: ready for review

#382 SPIKE: Namespace send-back events
  app/controllers/nsm/claims_controller.rb
  app/controllers/prior_authority/assignments_controller.rb
  app/controllers/prior_authority/unassignments_controller.rb
  app/forms/nsm/change_risk_form.rb
  app/forms/nsm/claim_note_form.rb
  app/forms/nsm/make_decision_form.rb
  app/forms/nsm/send_back_form.rb
  app/forms/nsm/unassignment_form.rb
  app/forms/prior_authority/decision_form.rb
  app/forms/prior_authority/send_back_form.rb
  app/models/event.rb
  app/models/event/draft_send_back.rb
  app/models/event/send_back.rb
  app/models/nsm/event/send_back.rb
  app/models/prior_authority/event/draft_send_back.rb
  app/models/prior_authority/event/send_back.rb
  app/view_models/prior_authority/v1/event_summary.rb
  config/locales/en/events.yml
  config/schedule.yml
  spec/forms/nsm/send_back_form_spec.rb
  spec/forms/prior_authority/send_back_form_spec.rb
  spec/mailers/prior_authority/feedback_messages/further_information_request_feeback_spec.rb
  spec/mailers/prior_authority/submission_feedback_mailer_spec.rb
  spec/models/event/send_back_spec.rb
  spec/system/nsm/history_spec.rb
  spec/system/prior_authority/history_spec.rb
Labels: approved

#386 Put further information request in more useful format
  app/forms/prior_authority/send_back_form.rb
  spec/forms/prior_authority/send_back_form_spec.rb
Labels: approved, ready for review

#390 Remove edit link when not editable
  app/views/prior_authority/applications/_primary_quote_card.html.erb
  app/views/prior_authority/applications/show.html.erb
Labels: approved

#394 CRM457-1273: Make layout more consistent and avoid rows inside columns
  app/views/nsm/adjustments/show.html.erb
  app/views/nsm/claim_details/show.html.erb
  app/views/nsm/histories/show.html.erb
  app/views/nsm/supporting_evidences/show.html.erb
Labels: bug, ready for review

#393 CRM457-992: QA feedback tweaks
  app/forms/base_adjustment_form.rb
  app/forms/nsm/base_adjustment_form.rb
  app/forms/prior_authority/base_cost_adjustment_form.rb
  app/forms/prior_authority/travel_cost_form.rb
  app/views/prior_authority/service_costs/edit.html.erb
  config/locales/en/prior_authority/service_costs.yml
  spec/system/prior_authority/adjust_service_costs_spec.rb
Labels: approved, In QA

#373 CRM457-1235: Delete adjustments
  app/controllers/prior_authority/additional_costs_controller.rb
  app/controllers/prior_authority/service_costs_controller.rb
  app/controllers/prior_authority/travel_costs_controller.rb
  app/models/event/undo_edit.rb
  app/services/prior_authority/adjustment_deleter.rb
  app/view_models/prior_authority/additional_costs_with_adjustments.rb
  app/view_models/prior_authority/service_costs_with_adjustments.rb
  app/view_models/prior_authority/travel_costs_with_adjustments.rb
  app/view_models/prior_authority/v1/quote.rb
  app/views/prior_authority/adjustments/_additional_costs.html.erb
  app/views/prior_authority/adjustments/_service_costs.html.erb
  app/views/prior_authority/adjustments/_travel_costs.erb
  app/views/prior_authority/shared/confirm_delete_adjustment.html.erb
  config/locales/en/prior_authority/additional_costs.yml
  config/locales/en/prior_authority/adjustments.yml
  config/locales/en/prior_authority/confirm_deletion.yml
  config/locales/en/prior_authority/service_costs.yml
  config/locales/en/prior_authority/service_types.yml
  config/locales/en/prior_authority/travel_costs.yml
  config/routes.rb
  spec/services/prior_authority/adjustment_deleter_spec.rb
  spec/system/prior_authority/delete_adjustments_spec.rb
Labels: approved, In QA
