Repository ministryofjustice/laa-assess-crime-forms, pull requests merged in 2025-01, with the labels that each got.

#900 [CRM-1792] bump common gem
  Gemfile
  Gemfile.lock
Labels: approved

#899 CRM457-2377 Adds GDPR message if deleted
  app/models/claim.rb
  app/view_models/nsm/v1/further_information.rb
  app/views/nsm/supporting_evidences/show.html.erb
  app/views/shared/_gdpr_documents_deleted.erb
  config/locales/en.yml
  spec/models/claims_spec.rb
  spec/system/nsm/overview_spec.rb
  spec/system/nsm/supporting_evidence_spec.rb
  spec/view_models/nsm/v1/further_information_spec.rb
Labels: ready for review

#905 CRM457-2405 Adds feedback url
  app/controllers/about/feedback_controller.rb
  app/mailers/feedback_mailer.rb
  app/models/feedback.rb
  app/views/about/feedback/index.html.erb
  app/views/layouts/_footer_links.html.erb
  app/views/layouts/_phase_banner.html.erb
  app/views/layouts/application.html.erb
  app/views/layouts/nsm.html.erb
  app/views/layouts/prior_authority.html.erb
  config/application.rb
  config/locales/en/feedback.yml
  spec/controllers/about/feedback_controller_spec.rb
  spec/mailers/feedback_mailer_spec.rb
  spec/system/accessibility_spec.rb
  spec/system/feedback_spec.rb
Labels: do not merge, approved
